{
  "hash": "713c9bc1656f9c2618bdf2afabb6052a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Model Prediction/Visualisation <br> 1. The Basics\"\ndate: 2025-03-21\ncategories: [code, concept, modelling, visualisation]\nimage: \"images/plot.png\"\ndescription: \"How to predict from your model.\"\n---\n\n\nMost of you will be familiar with how to create and run a statistical model in `R`. But what do you then do with your model results? I bet you take `R`'s rather bland console output, convert that to a formatted table in your manuscript, then based on the regression coefficient values, go on and talk about associations of your exposure/s with your outcome.\n\nAnd leave it at that.\n\nWell, the old adage of \"a picture is worth a thousand words\" has never been truer in the context of model prediction and how much additional information value you can obtain if you take your analyses a step further. Our reliance on just looking at the numbers (i.e. the regression coefficients) is sufficient a lot of the time in simple cases, but when models become a more complex - for example, by the specification of non-linear covariate functional forms via splines - regression coefficients on their own are essentially useless in aiding our interpretation. Plotting the model predictions, however, can put us back on track for understanding the important relationships in our data. Even a complex model can make more sense when we can visualise its predictions. These are skills worth learning and adding to your data analyst toolkit.\n\nSo, I thought I would put together a series of posts on predicting from and visualising your model, where in each post we cover a different area related to the subject. This week it's just about the basics of model prediction and visualisation, but in future posts I hope to extend those ideas to more advanced topics including non-linear functional forms, glm's, mixed-models, etc (let's see how we go). But first, let's start at the start...\n\n# What is Model Prediction\n\nWhen we specify a model using traditional `lm()` syntax in `R`, remember that we are just re-expressing the fundamental regression equation you will find in any statistical textbook:\n\n$$ \\hat{y} = \\beta_0 + \\beta_1 x_1 + \\beta_2 x_2 + ... $$\n\nWhere:\n\n$\\beta_0$ is the intercept (the expected value of $y$ when $x_1$ and $x_2$ are both equal to `0`);\n\n$\\beta_1$ and $\\beta_2$ are the regression coefficients for $x_1$ and $x_2$, respectively, and;\n\n$\\beta_1$ is the expected *change* in $y$ for a one-unit change in $x_1$ (when $x_2$ is held at a constant value);\n\n$\\beta_2$ is the expected *change* in $y$ for a one-unit change in $x_2$ (when $x_1$ is held at a constant value).\n\nThe coefficents in the regression equation define the relationship between each independent variable (exposure/predictor) and the dependent variable (outcome). But you don't need to stop there - it's very easy to enter values for the independent variables into the equation to also predict the expected (mean) value of the dependent variable. Let's take a look at a very simple example that uses the built-in `mtcars` dataset in `R`. Say we want to examine the relationship between fuel economy (miles/gallon \\[`mpg`\\]) and weight and transmission type (`wt + am`). A standard linear regression gives:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(kableExtra)\ndata(mtcars)\nsummary(lm(mpg ~ wt + am, data = mtcars))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mpg ~ wt + am, data = mtcars)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.5295 -2.3619 -0.1317  1.4025  6.8782 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 37.32155    3.05464  12.218 5.84e-13 ***\nwt          -5.35281    0.78824  -6.791 1.87e-07 ***\nam          -0.02362    1.54565  -0.015    0.988    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.098 on 29 degrees of freedom\nMultiple R-squared:  0.7528,\tAdjusted R-squared:  0.7358 \nF-statistic: 44.17 on 2 and 29 DF,  p-value: 1.579e-09\n```\n\n\n:::\n:::\n\n\nInterpreting just the regression coefficients, we could say that on average, a one-unit increase in weight (which corresponds here to `1000` pounds) is associated with a reduction in fuel economy of `5.4` mpg when transmission type is held constant. Similary, we can also say that on average, a one-unit increase in transmission type (which corresponds here to simply changing from an automatic to manual car) is associated with a barely notable reduction in fuel economy of `0.02` mpg, when weight is held constant.\n\nBut we can use this model to make some simple predictions as well. You might want to know what is the expected fuel economy for a manual, `5000` pound car (not very good I would think). Well it's a simple exercise in substitution:\n\n$$ \\hat{y} = 37.3 - 5.4 * 5 - 0.02 * 0 = 10.3 $$\n\nOk, what about the economy of a much lighter, automatic, `2000` pound vehicle?\n\n$$ \\hat{y} = 37.3 - 5.4 * 2 - 0.02 * 1 = 26.5 $$\n\nThat's all that prediction is, really - substitution into your regression equation. Prediction in this context isn't about predicting the future - in fact for most simple models, time plays no role (although it may, depending on the research question and the model we are using). We are typically more interested in predicting the mean value of the dependent variable given specific values of the independent variable/s.\n\nWhile you can predict for any combination of covariate values, the visualisation of model predictions comes into its own when we focus on the relationship between some exposure and an outcome, holding the values of all other covariates in the model fixed. These are, in other words, **adjusted** predictions, and can help you to answer the question: \"What is the expected outcome for certain values or levels of my exposure, when I have removed any other potential confounding effects?\"\n\nAlright, I think you get enough of an idea that we can actually now take a look at a more concrete example.\n\n# `birthwt` Dataset\n\nIn our very first example to show you how to get up and running with predicting and visualising from your model, we will use the `birthwt` dataset that comes with the `MASS` package. A listing of the variables can be found [here](https://vincentarelbundock.github.io/Rdatasets/doc/MASS/birthwt.html), and the first `10` rows of the dataframe look like:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(birthwt, package = \"MASS\")\nhead(birthwt, 10)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   | low| age| lwt| race| smoke| ptl| ht| ui| ftv|  bwt|\n|:--|---:|---:|---:|----:|-----:|---:|--:|--:|---:|----:|\n|85 |   0|  19| 182|    2|     0|   0|  0|  1|   0| 2523|\n|86 |   0|  33| 155|    3|     0|   0|  0|  0|   3| 2551|\n|87 |   0|  20| 105|    1|     1|   0|  0|  0|   1| 2557|\n|88 |   0|  21| 108|    1|     1|   0|  0|  1|   2| 2594|\n|89 |   0|  18| 107|    1|     1|   0|  0|  1|   0| 2600|\n|91 |   0|  21| 124|    3|     0|   0|  0|  0|   0| 2622|\n|92 |   0|  22| 118|    1|     0|   0|  0|  0|   1| 2637|\n|93 |   0|  17| 103|    3|     0|   0|  0|  0|   1| 2637|\n|94 |   0|  29| 123|    1|     1|   0|  0|  0|   1| 2663|\n|95 |   0|  26| 113|    1|     1|   0|  0|  0|   0| 2665|\n\n</div>\n:::\n:::\n\n\n## Birthweight as a Function of Maternal Age\n\nLet's initially consider the possible association between baby birthweight (`bwt` - outcome) and mother's `age` (exposure). We will run the model as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod <-  lm(bwt ~ age, data = birthwt)\nsummary(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bwt ~ age, data = birthwt)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2294.78  -517.63    10.51   530.80  1774.92 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  2655.74     238.86   11.12   <2e-16 ***\nage            12.43      10.02    1.24    0.216    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 728.2 on 187 degrees of freedom\nMultiple R-squared:  0.008157,\tAdjusted R-squared:  0.002853 \nF-statistic: 1.538 on 1 and 187 DF,  p-value: 0.2165\n```\n\n\n:::\n:::\n\n\nThe model seems to suggest that increasing maternal age is associated with increasing birthweight. Keep in mind that this is unlikely to represent reality and I would guess that the relationship between maternal age and birthweight is non-linear (i.e. at some maternal age, birthweight is more likely to start decreasing with increasing maternal age). But for the sake of today's exercise let's just assume the relationship is linear.\n\n### Predict\n\nCalculating predictions from the model is as simple as using the `predict()` function following your model call, adding the predictions as a new column to the original dataframe (or creating a new dataframe if you desire). Here I will just add the new column containing the predictions to a new dataframe containing only the relevant variables, and print the first `10` rows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirthwt2 <-  birthwt |> \n  select(bwt, age) |> \n  mutate(pred = predict(mod))\nhead(birthwt2, 10) |> \n  kable(align = \"c\", digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n|   | bwt  | age |  pred  |\n|:--|:----:|:---:|:------:|\n|85 | 2523 | 19  | 2891.9 |\n|86 | 2551 | 33  | 3065.9 |\n|87 | 2557 | 20  | 2904.3 |\n|88 | 2594 | 21  | 2916.8 |\n|89 | 2600 | 18  | 2879.5 |\n|91 | 2622 | 21  | 2916.8 |\n|92 | 2637 | 22  | 2929.2 |\n|93 | 2637 | 17  | 2867.0 |\n|94 | 2663 | 29  | 3016.2 |\n|95 | 2665 | 26  | 2978.9 |\n\n\n:::\n:::\n\n\n### Visualise\n\nPlotting the model predictions is simple using `ggplot2`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(birthwt2, aes(x = age, y = pred)) +\n  geom_line(linewidth = 1)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=1152}\n:::\n:::\n\n\nIt can be useful to add in the raw datapoints, so let's do that, and I'll add a couple of plotting embellishments as well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = birthwt2, aes(x = age, y = pred)) +\n  geom_line(linewidth = 1) +\n  geom_point(data = birthwt2, aes(x = age, y = bwt)) +\n  xlab(\"Maternal Age\") + ylab(\"Predicted Birthweight\") +\n  theme_bw(base_size = 20)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=1152}\n:::\n:::\n\n\nGreat! We've generated predictions from our model and visualised the results. That wasn't too hard.\n\n## Birthweight as a Function of Maternal Age and Smoking\n\nLet's take it up a step by now including maternal smoking (`smoke`) as another exposure in our model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod2 <-  lm(bwt ~ age + smoke, data = birthwt)\nsummary(mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bwt ~ age + smoke, data = birthwt)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2119.98  -442.66    52.92   532.38  1690.74 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 2791.224    240.950  11.584   <2e-16 ***\nage           11.290      9.881   1.143    0.255    \nsmoke       -278.356    106.987  -2.602    0.010 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 717.2 on 186 degrees of freedom\nMultiple R-squared:  0.04299,\tAdjusted R-squared:  0.0327 \nF-statistic: 4.177 on 2 and 186 DF,  p-value: 0.0168\n```\n\n\n:::\n:::\n\n\nSo, the coefficient for `age` hasn't really changed that much, but we can see that smoking seems to have a significant impact, decreasing birthweight on average by `278` grams.\n\nLet's predict birthweight from this model as we did before:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirthwt2 <-  birthwt |> \n  select(bwt, age, smoke) |> \n  mutate(pred = predict(mod2))\nhead(birthwt2, 10) |> \n  kable(align = \"c\", digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n|   | bwt  | age | smoke |  pred  |\n|:--|:----:|:---:|:-----:|:------:|\n|85 | 2523 | 19  |   0   | 3005.7 |\n|86 | 2551 | 33  |   0   | 3163.8 |\n|87 | 2557 | 20  |   1   | 2738.7 |\n|88 | 2594 | 21  |   1   | 2749.9 |\n|89 | 2600 | 18  |   1   | 2716.1 |\n|91 | 2622 | 21  |   0   | 3028.3 |\n|92 | 2637 | 22  |   0   | 3039.6 |\n|93 | 2637 | 17  |   0   | 2983.1 |\n|94 | 2663 | 29  |   1   | 2840.3 |\n|95 | 2665 | 26  |   1   | 2806.4 |\n\n\n:::\n:::\n\n\nAnd plot the predictions as we did before:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = birthwt2, aes(x = age, y = pred)) +\n  geom_line(linewidth = 1) +\n  geom_point(data = birthwt2, aes(x = age, y = bwt)) +\n  xlab(\"Maternal Age\") + ylab(\"Predicted Birthweight\") +\n  theme_bw(base_size = 20)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=1152}\n:::\n:::\n\n\nUh-oh! Something has obviously gone badly wrong.\n\nThe problem is that we have **predicted on the original data** and the predictions are the result of the combination of each woman's unique values of both maternal age **and** smoking status. In other words, we are not just plotting the predicted value of birthweight as a function of maternal age alone, but rather as a function of both maternal age and smoking status. We are then trying to visualise those predictions as if they were generated from a function of maternal age alone.\n\nAs you can then see - \"Computer says no\".\n\nTo properly visualise predictions when more than one predictor are involved, requires that we find a way to generate the adjusted predictions I mentioned earlier. And, of course, there's a fairly easy way to do that in `R`.\n\n### Predict\n\nWhen you have more than one covariate in your model, **predicting on new data** will allow you to generate the adjusted predictions that facilitate sensible visualisation. The `predict()` function actually contains a `newdata` argument that you can point towards a 'grid' of specified covariate values to predict on. This 'grid' is essentially a new dataframe that contains all possible combinations of covariates at salient values (typically a range of values at set intervals for numeric variables and every category/level for factor variables). In this way (adjusted) predictions can be made for one variable while keeping the other variable/s at fixed values.\n\nTo construct the grid of new data, we will use the [`expand.grid()`](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/expand.grid) function. I will specify a maternal age range from `15` to `45` in `5` year intervals and a smoking status variable equal to either `0` or `1`. This grid of new data (which I have called `newdf`) looks like:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnewdf <-  expand.grid(age = seq(15, 45, by = 5),\n                      smoke = c(0,1))\nnewdf |> \n  kable(align = \"c\", digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n| age | smoke |\n|:---:|:-----:|\n| 15  |   0   |\n| 20  |   0   |\n| 25  |   0   |\n| 30  |   0   |\n| 35  |   0   |\n| 40  |   0   |\n| 45  |   0   |\n| 15  |   1   |\n| 20  |   1   |\n| 25  |   1   |\n| 30  |   1   |\n| 35  |   1   |\n| 40  |   1   |\n| 45  |   1   |\n\n\n:::\n:::\n\n\n::: callout-important\nNote that the variable names in your new dataframe **MUST** match the names of the corresponding variables in your original dataset, otherwise `predict()` will become upset with you and refuse to do any more work.\n:::\n\nNow we are in a position to generate the predictions that we need. Nothing changes compared to before, except we now specify a new dataframe to predict upon using the `newdata` argument:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnewdf <-  newdf |> \n  mutate(pred = predict(mod2, newdata = newdf))\nnewdf |> \n  kable(align = \"c\", digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n| age | smoke |  pred  |\n|:---:|:-----:|:------:|\n| 15  |   0   | 2960.6 |\n| 20  |   0   | 3017.0 |\n| 25  |   0   | 3073.5 |\n| 30  |   0   | 3129.9 |\n| 35  |   0   | 3186.4 |\n| 40  |   0   | 3242.8 |\n| 45  |   0   | 3299.3 |\n| 15  |   1   | 2682.2 |\n| 20  |   1   | 2738.7 |\n| 25  |   1   | 2795.1 |\n| 30  |   1   | 2851.6 |\n| 35  |   1   | 2908.0 |\n| 40  |   1   | 2964.5 |\n| 45  |   1   | 3020.9 |\n\n\n:::\n:::\n\n\n### Visualise\n\nThe key when we come to plotting the predictions is to now realise that because we are representing age on the x-axis, we need to use some other means to represent smoking status. In this case we can do that quite easily by using the colour aesthetic in our `ggplot` call:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = newdf, aes(x = age, y = pred, color = factor(smoke))) +\n  geom_line(linewidth = 1) +\n  geom_point(data = birthwt2, aes(x = age, y = bwt), size = 2) +\n  xlab(\"Maternal Age\") + ylab(\"Predicted Birthweight\") + labs(color = \"Smoking Status\") +\n  theme_bw(base_size = 20) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=1152}\n:::\n:::\n\n\nNote that I converted smoking status to a factor variable on the fly so that `ggplot` knows that it only has two levels (otherwise it assumes it's a continuous variable).\n\nSo, what do we actually have here, when I call this a plot of adjusted predictions? We have two parallel regression lines - one for smokers (blue) and one for non-smokers (red). They are parallel because 'effects' are additive - we did not specify an interaction between maternal age and smoking status. The red line is the predicted birthweight as a function of maternal age for non-smoking mothers and the blue line is the predicted birthweight as a function of maternal age for smoking mothers. In other words, predictions of the association between maternal age and newborn birthweight, adjusted for maternal smoking status (we can flip this around and also say that these are predictions of the association between smoking status and newborn birthweight, adjusted for maternal age). The regression line/s no longer zig-zag, like they did in the earlier plot, because we have separated out the 'effect' of the second exposure from the first allowing a 'pure' association between maternal age and newborn birthweight at each level of smoking status to be observed.\n\nThese same principles of prediction and visualisation can be applied in nearly all model plotting endeavours. There does, however, become a limit in the number of covariates that can practically be visualised and that is something we will look at in more detail in the next post.\n\nI will conclude by saying that for this series I am going to illustrate all concepts using what I consider to be 'first principles' - that is, applying the `predict()` and `expand.grid()` functions for predicting, and `ggplot2` for visualising. But there may be better/faster ways to do this and a package I came across recently that I think would be worthwhile exploring is [`ggeffects`](https://strengejacke.github.io/ggeffects/index.html). I haven't used this myself but a quick scan of the package website gives me the impression this will make even shorter work of my 'first principles' approach. It is a package that I will keep in mind as we go forward on this topic.\n\nCatch you in a couple of weeks...\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}