---
title: "Immortal time bias - \"The fallacy that never dies\" (Part 2)"
date: 2024-02-16
categories: [code, analysis, modelling, survival, visualisation]
#image: 
description: "Let's investigate immortal time bias with a coded example."
---

```{r}
#| message: false
#| warning: false
library(survival)
library(survminer)
data(heart, package="survival")
head(jasa)
```

```{r}
# Visualise survival trajectories of random sample of women

jasa$id <- seq(1:dim(jasa)[1])
temp <- jasa
temp$wait.time[is.na(temp$wait.time)] <- temp$futime[is.na(temp$wait.time)]

temp |> # Use this to sort 2 groups in plot
  ggplot(aes(x = id, y = futime)) +
  geom_linerange(aes(ymin = 0, ymax = wait.time), color = "#E7B800", linewidth = 1) +
  geom_linerange(aes(ymin = wait.time, ymax = futime), color = "#2E9FDF", linewidth = 1) +
  geom_point(aes(shape = factor(fustat)), stroke = 1, cex = 1, color = "black") +
  scale_shape_manual(values = c(1, 3), labels = c("Censored", "Died"), name = "Outcome") +
  annotate("text", x = 95, y = 1400, label = "Observation time = yellow - untransplanted", size = 5, color = "#E7B800") +
  annotate("text", x = 92, y = 1380, label = "Observation time = blue - post-transplant", size = 5, color = "#2E9FDF") +
  ggtitle("Survival Trajectories for Heart Transplant Patients") +   
  ylab("Time (days)") +
  xlab("Patient Number") + 
  coord_flip() + 
  theme_bw(base_size = 15) +
  theme(axis.text.y = element_text(size = 15))
```


```{r}
fit <- survfit(Surv(futime, fustat) ~ transplant, data = jasa)
ggsurvplot(fit,
          pval = TRUE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "strata", # Change risk table color by groups
          linetype = "strata", # Change line type by groups
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw(), # Change ggplot2 theme
          palette = c("#E7B800", "#2E9FDF"))
```

```{r}
mod <- coxph(Surv(futime, fustat) ~ transplant, data = jasa)
summary(mod)
```

