<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-06-27">
<meta name="description" content="The hazards of misunderstanding the hazard ratio.">

<title>Test Site 2 - Are your Hazards Proportional? - What to do when it just ain’t so (Part 1)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Test Site 2</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">All Posts</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background"><span class="header-section-number">1</span> Background</a></li>
  <li><a href="#proportional-hazards-in-a-nutshell" id="toc-proportional-hazards-in-a-nutshell" class="nav-link" data-scroll-target="#proportional-hazards-in-a-nutshell"><span class="header-section-number">2</span> Proportional Hazards (in a Nutshell)</a></li>
  <li><a href="#tvcs-vs-tvcs" id="toc-tvcs-vs-tvcs" class="nav-link" data-scroll-target="#tvcs-vs-tvcs"><span class="header-section-number">3</span> tvc’s vs tvc’s</a>
  <ul>
  <li><a href="#tvc-time-varying-covariate" id="toc-tvc-time-varying-covariate" class="nav-link" data-scroll-target="#tvc-time-varying-covariate"><span class="header-section-number">3.1</span> tvc (time-varying covariate)</a></li>
  <li><a href="#tvc-time-varying-coefficient" id="toc-tvc-time-varying-coefficient" class="nav-link" data-scroll-target="#tvc-time-varying-coefficient"><span class="header-section-number">3.2</span> tvc (time-varying coefficient)</a></li>
  <li><a href="#well-is-it-tvc-or-tvc" id="toc-well-is-it-tvc-or-tvc" class="nav-link" data-scroll-target="#well-is-it-tvc-or-tvc"><span class="header-section-number">3.3</span> Well is it tvc or tvc?</a></li>
  </ul></li>
  <li><a href="#testing-for-proportional-hazards" id="toc-testing-for-proportional-hazards" class="nav-link" data-scroll-target="#testing-for-proportional-hazards"><span class="header-section-number">4</span> Testing for Proportional Hazards</a>
  <ul>
  <li><a href="#goodness-of-fit-gof-tests." id="toc-goodness-of-fit-gof-tests." class="nav-link" data-scroll-target="#goodness-of-fit-gof-tests."><span class="header-section-number">4.1</span> Goodness of Fit (GOF) tests.</a></li>
  <li><a href="#graphical-assessment." id="toc-graphical-assessment." class="nav-link" data-scroll-target="#graphical-assessment."><span class="header-section-number">4.2</span> Graphical assessment.</a></li>
  <li><a href="#time-dependent-variables." id="toc-time-dependent-variables." class="nav-link" data-scroll-target="#time-dependent-variables."><span class="header-section-number">4.3</span> Time-dependent variables.</a>
  <ul class="collapse">
  <li><a href="#one-simple-rule-about-covariate-values-in-the-cox-model" id="toc-one-simple-rule-about-covariate-values-in-the-cox-model" class="nav-link" data-scroll-target="#one-simple-rule-about-covariate-values-in-the-cox-model"><span class="header-section-number">4.3.1</span> One simple rule about covariate values in the Cox model</a></li>
  <li><a href="#event-times-are-all-important-in-the-cox-model" id="toc-event-times-are-all-important-in-the-cox-model" class="nav-link" data-scroll-target="#event-times-are-all-important-in-the-cox-model"><span class="header-section-number">4.3.2</span> Event times are all-important in the Cox model</a></li>
  <li><a href="#putting-it-all-together" id="toc-putting-it-all-together" class="nav-link" data-scroll-target="#putting-it-all-together"><span class="header-section-number">4.3.3</span> Putting it all together</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#wrap-up" id="toc-wrap-up" class="nav-link" data-scroll-target="#wrap-up"><span class="header-section-number">5</span> Wrap-Up</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Are your Hazards Proportional? - What to do when it just ain’t so (Part 1)</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">code</div>
    <div class="quarto-category">concept</div>
    <div class="quarto-category">modelling</div>
    <div class="quarto-category">visualisation</div>
  </div>
  </div>

<div>
  <div class="description">
    The hazards of misunderstanding the hazard ratio.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 27, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="background" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Background</h1>
<p>Ok, I’m going to be a bit melodramatic here, but bear with me. Have you ever felt like crying when your carefully constructed Cox model - one that is giving you the significant ‘effect/s’ you’ve been dreaming of - fails at the last hurdle when you discover that one (or more) of its covariates violates the assumption of proportional hazards?</p>
<p>Or is that just me?</p>
<p>The Cox model is ubiquitous in medical research and is typically utilised when questions develop around assessing the time to some outcome of interest. Like any other mathematical model, the Cox model is capable of capturing only a simple reflection of biological systems that are much more complex in reality. To that end assumptions are made about the nature of the data that the model is expected to parse, and the greater the violation of those assumptions, the less faithful one can expect the reflection to be. In other words, the model becomes less and less trustworthy.</p>
<p>Where am I headed with my ham-fisted attempt at philosophising? Well, as I’m sure you know, one of the primary assumptions underpinning the Cox model is that of proportional hazards. I have actually discussed this in one of my <a href="https://msni-stats-tips.netlify.app/posts/021_01nov_2024/#semi-parametric-cox-model">previous posts on survival analysis</a> when I introduced the Cox model, but it’s so important I’m going to reiterate here.</p>
</section>
<section id="proportional-hazards-in-a-nutshell" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Proportional Hazards (in a Nutshell)</h1>
<p>The following is what I said in that post:</p>
<p>“The proportional hazards assumption basically requires that the hazard ratio (HR) is constant over time, or equivalently, that the hazard for one individual is proportional to the hazard for any other individual, and where the proportionality constant doesn’t depend on time.</p>
<p>So if we look at the figure below - I have plotted hypothetical hazard functions for males (in blue) and females (in red) for the risk of some event. You’ll note that the shapes are essentially the same but are scaled versions of one another. When proportional hazards hold, then we can take a ratio of the two hazard rates at any time point and that ratio should remain constant. And I’ve illustrated that here at two time points - <span class="math inline">\(t1\)</span> and <span class="math inline">\(t2\)</span>. The difference in the hazards obviously varies but the ratio of the hazards at those two time points is the same. At time <code>1</code> a hazard rate of <code>3</code> for males and <code>2</code> for females gives a HR of <code>1.5</code> and similarly, at time <code>2</code>, a hazard rate of <code>0.75</code> for males and <code>0.5</code> for females, again gives a HR of <code>1.5</code>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/prop_hazards.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p><strong>In reality, hazard rates are probably not going to be exactly proportional the entire time, but the aim is to make sure any departures from proportionality are minimal - otherwise this means the HR itself varies with time and this adds further complexity to your model.</strong>”</p>
<p>All of that remains true, but the last paragraph is particularly important in the context of this week’s topic. In general, we just tend to assume the HR that is output by <code>coxph()</code> is valid over the entire duration of observation when this is unlikely to be the case. If hazards are in fact non-proportional and we still accept that HR as the single ‘effect’ estimate, then it represents an <strong>averaged HR</strong> over the observation period (this <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC3653612/">paper</a> discusses this issue - and more - in greater detail). Small departures from proportionality are probably still OK, but it’s the larger departures that become more problematic in our model validity. The good news is there are steps we can take to test for these departures and that is ultimately the focus of today’s post.</p>
</section>
<section id="tvcs-vs-tvcs" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> tvc’s vs tvc’s</h1>
<p>Before we go any further I think it is important to clarify a couple of related but distinct concepts regarding “time variation” in survival analyses, as “tvc” is an acronym with two different definitions depending on the context in which it is used.</p>
<section id="tvc-time-varying-covariate" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="tvc-time-varying-covariate"><span class="header-section-number">3.1</span> tvc (time-varying covariate)</h2>
<p>In perhaps the more common usage, “tvc” can represent a <em>time-varying covariate</em> (also known as time-dependent covariate (tdc)). This is a covariate whose <em>values change</em> over the duration of one’s observation period, but whose <em>‘effect’ on survival typically remains constant.</em> A good example here would be different time periods in which a person received treatment or not. Time-varying covariates are constructed as multi-row (i.e.&nbsp;<a href="https://msni-stats-tips.netlify.app/posts/006_23feb_2024/#correct-analysis-assuming-treatment-status-is-time-varying">counting process</a>) data where each row contains a non-overlapping time period defined by a different treatment covariate value. Proportional hazards may still be assessed with counting process data and if no violation is noted, <strong>a constant HR over the duration of observation</strong> may be assumed.</p>
</section>
<section id="tvc-time-varying-coefficient" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="tvc-time-varying-coefficient"><span class="header-section-number">3.2</span> tvc (time-varying coefficient)</h2>
<p>Now, without intending to create confusion, “tvc” may also represent a <em>time-varying coefficient</em> (also known as time-dependent coefficient (tdc)). This is associated with a covariate whose baseline <em>values remain constant</em> over the duration of observation, but whose <em>‘effect’ on the risk of an event can indeed change with time.</em> <strong>In other words, the HR varies with time.</strong> Data are typically formatted as one-row per person.</p>
</section>
<section id="well-is-it-tvc-or-tvc" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="well-is-it-tvc-or-tvc"><span class="header-section-number">3.3</span> Well is it tvc or tvc?</h2>
<p>In a survival analysis, one may have:</p>
<ol type="1">
<li><p>Neither time-varying covariates nor time-varying coefficients (single-row/person, constant HR).</p></li>
<li><p>Time-varying coefficients but not time-varying covariates (single-row/person, time-varying HR).</p></li>
<li><p>Time-varying covariates but not time-varying coefficients (multi-row/person, constant HR).</p></li>
<li><p>Time-varying coefficients and time-varying covariates (multi-row/person, time-varying HR).</p></li>
</ol>
<p>In today’s post, the examples and discussion I provide will only focus on scenario 2. The addition of time-varying covariates into analyses with time-varying coefficients (scenario 4) complicates matters significantly and I’ve made the decision not to tackle this for the time being (although I may come back to this in a later post).</p>
<p>But now that we’ve cleared that up, let’s get back to the issue at hand.</p>
</section>
</section>
<section id="testing-for-proportional-hazards" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Testing for Proportional Hazards</h1>
<p>There are essentially three approaches to testing the proportional hazards assumption, although dare I say most of us probably only ever use the first.</p>
<ol type="1">
<li>Goodness of Fit (GOF) tests.</li>
<li>Graphical assessment.</li>
<li>Time-dependent variables.</li>
</ol>
<p>To illustrate these approaches we’ll use the <code>veteran</code> dataset that is built into <code>R</code>’s <code>survival</code> package. Details can be found <a href="https://www.rdocumentation.org/packages/survival/versions/3.8-3/topics/veteran">here</a> but, in brief, the data consist of survival times for <code>137</code> lung-cancer sufferers enrolled in an RCT of two treatment regimens. The variables of interest for the purpose of today’s exercise are:</p>
<ul>
<li><p><code>time</code> - survival time (days)</p></li>
<li><p><code>status</code> - censor (0), death (1)</p></li>
<li><p><code>trt</code> - treatment [standard (1) vs test (2)]</p></li>
<li><p><code>age</code> - age (yrs)</p></li>
</ul>
<p>We’ll consider <code>trt</code> our primary “exposure” of interest and <code>age</code> a covariate to adjust for. The first few rows of the data look like:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="fu">library</span>(survminer)</span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb1-5"><a href="#cb1-5"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-6"><a href="#cb1-6"></a><span class="co"># Load veteran data from survival package</span></span>
<span id="cb1-7"><a href="#cb1-7"></a>vdata1 <span class="ot">&lt;-</span>  veteran</span>
<span id="cb1-8"><a href="#cb1-8"></a><span class="co"># Make treatment variable equal to 0,1 instead of 1,2 (not necessary, but I just like to work with the former)</span></span>
<span id="cb1-9"><a href="#cb1-9"></a>vdata1<span class="sc">$</span>trt <span class="ot">&lt;-</span>  <span class="fu">as.numeric</span>(vdata1<span class="sc">$</span>trt) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb1-10"><a href="#cb1-10"></a><span class="co"># Create id variable and organise columns</span></span>
<span id="cb1-11"><a href="#cb1-11"></a>vdata1<span class="sc">$</span>id <span class="ot">&lt;-</span>  <span class="fu">seq</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">dim</span>(vdata1)[<span class="dv">1</span>])</span>
<span id="cb1-12"><a href="#cb1-12"></a>vdata1 <span class="ot">&lt;-</span>  vdata1 <span class="sc">|&gt;</span> </span>
<span id="cb1-13"><a href="#cb1-13"></a>  <span class="fu">select</span>(id, time, status, trt, age)</span>
<span id="cb1-14"><a href="#cb1-14"></a><span class="fu">head</span>(vdata1, <span class="dv">10</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-15"><a href="#cb1-15"></a>  <span class="fu">kable</span>(<span class="at">align =</span> <span class="st">"c"</span>, <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">id</th>
<th style="text-align: center;">time</th>
<th style="text-align: center;">status</th>
<th style="text-align: center;">trt</th>
<th style="text-align: center;">age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">72</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">69</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">411</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">64</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">228</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">38</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">126</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">63</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">118</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">65</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">49</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;">82</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">69</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">110</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">68</td>
</tr>
<tr class="odd">
<td style="text-align: center;">9</td>
<td style="text-align: center;">314</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">43</td>
</tr>
<tr class="even">
<td style="text-align: center;">10</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">70</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<p>As a precursor step let’s plot the Kaplan-Meier curves for these data - for no other reason than to calibrate our expectations for the upcoming proportional hazards tests.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># Kaplan-Meier plot</span></span>
<span id="cb2-2"><a href="#cb2-2"></a>km_trt_fit <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> trt, <span class="at">data =</span> veteran)</span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="fu">ggsurvplot</span>(km_trt_fit, <span class="at">data =</span> veteran, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">"#E7B800"</span>, <span class="st">"#2E9FDF"</span>), <span class="at">conf.int =</span> F,</span>
<span id="cb2-4"><a href="#cb2-4"></a>           <span class="at">legend.labs =</span> <span class="fu">c</span>(<span class="st">"standard"</span>, <span class="st">"test"</span>), <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">20</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>OK, well this is interesting as it already tells us we have a problem with the <code>trt</code> variable. Survival curves should ideally gradually separate over time. When they appear to converge - or worse still <strong>cross</strong> - this should be a warning to us that the hazard function for one group is NOT a scaled function of the other (i.e.&nbsp;they are non-proportional with respect to time). While this is a fairly obvious violation in this example, it is not uncommon for non-proportionality to appear more subtle in KM plots leaving us unsure as to whether there may be a problem or not. Not to worry though - that’s why we have these additional tests we can employ, and which I will discuss now!</p>
<section id="goodness-of-fit-gof-tests." class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="goodness-of-fit-gof-tests."><span class="header-section-number">4.1</span> Goodness of Fit (GOF) tests.</h2>
<p>The classic GOF approach uses a test statistic and p-value to assess the significance of the PH assumption based on the Schoenfeld residuals of the Cox model (I won’t attempt to explain how these residuals are derived). Visually, if proportional hazards hold, then a plot of the scaled Schoenfeld residuals over time (for a particular covariate) should have zero slope. That is, we should ideally see a horizontal line which indicates that the residuals for that covariate are not related to survival time. In <code>R</code> we can use the <code>cox.zph()</code> function to perform a significance test for each covariate and for the model as a whole. Additionally, we can <code>plot()</code> the object returned by the <code>cox.zph()</code> call to visualise the shape of the resulting smoothed (loess) curve fitted to the residuals, for each covariate. <strong>It can be very helpful to take note of this functional form as that is how the HR for the covariate is expected to actually vary over time.</strong> This also provides a sanity check for any time-varying HR we might calculate later, if we decide to take remediation action in relaxing the assumption of proportionality in our model specification.</p>
<p>To test the proportional hazards assumption we first need to fit a Cox model, so let’s do that now.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="co"># Fit basic model with treatment and age as the only predictors</span></span>
<span id="cb3-2"><a href="#cb3-2"></a>vfit1 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> trt <span class="sc">+</span> age, vdata1)</span>
<span id="cb3-3"><a href="#cb3-3"></a><span class="fu">tbl_regression</span>(vfit1, <span class="at">exp =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="hakgllzqjh" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#hakgllzqjh table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#hakgllzqjh thead, #hakgllzqjh tbody, #hakgllzqjh tfoot, #hakgllzqjh tr, #hakgllzqjh td, #hakgllzqjh th {
  border-style: none;
}

#hakgllzqjh p {
  margin: 0;
  padding: 0;
}

#hakgllzqjh .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#hakgllzqjh .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#hakgllzqjh .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hakgllzqjh .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hakgllzqjh .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hakgllzqjh .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hakgllzqjh .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hakgllzqjh .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hakgllzqjh .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hakgllzqjh .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hakgllzqjh .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hakgllzqjh .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hakgllzqjh .gt_spanner_row {
  border-bottom-style: hidden;
}

#hakgllzqjh .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#hakgllzqjh .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hakgllzqjh .gt_from_md > :first-child {
  margin-top: 0;
}

#hakgllzqjh .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hakgllzqjh .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hakgllzqjh .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#hakgllzqjh .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#hakgllzqjh .gt_row_group_first td {
  border-top-width: 2px;
}

#hakgllzqjh .gt_row_group_first th {
  border-top-width: 2px;
}

#hakgllzqjh .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hakgllzqjh .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#hakgllzqjh .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#hakgllzqjh .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hakgllzqjh .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hakgllzqjh .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hakgllzqjh .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#hakgllzqjh .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hakgllzqjh .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hakgllzqjh .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hakgllzqjh .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hakgllzqjh .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hakgllzqjh .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hakgllzqjh .gt_left {
  text-align: left;
}

#hakgllzqjh .gt_center {
  text-align: center;
}

#hakgllzqjh .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hakgllzqjh .gt_font_normal {
  font-weight: normal;
}

#hakgllzqjh .gt_font_bold {
  font-weight: bold;
}

#hakgllzqjh .gt_font_italic {
  font-style: italic;
}

#hakgllzqjh .gt_super {
  font-size: 65%;
}

#hakgllzqjh .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#hakgllzqjh .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#hakgllzqjh .gt_indent_1 {
  text-indent: 5px;
}

#hakgllzqjh .gt_indent_2 {
  text-indent: 10px;
}

#hakgllzqjh .gt_indent_3 {
  text-indent: 15px;
}

#hakgllzqjh .gt_indent_4 {
  text-indent: 20px;
}

#hakgllzqjh .gt_indent_5 {
  text-indent: 25px;
}
</style>

<table class="gt_table table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="header gt_col_headings">
<th id="<strong>Characteristic</strong>" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="<strong>HR</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>HR</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
<th id="<strong>95% CI</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
<th id="<strong>p-value</strong>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">trt</td>
<td class="gt_row gt_center" headers="estimate">1.00</td>
<td class="gt_row gt_center" headers="ci">0.70, 1.42</td>
<td class="gt_row gt_center" headers="p.value">&gt;0.9</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">age</td>
<td class="gt_row gt_center" headers="estimate">1.01</td>
<td class="gt_row gt_center" headers="ci">0.99, 1.03</td>
<td class="gt_row gt_center" headers="p.value">0.4</td>
</tr>
</tbody><tfoot class="gt_footnotes">
<tr class="odd">
<td colspan="4" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> HR = Hazard Ratio, CI = Confidence Interval</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
<p>Based on these model results there does not appear to be much to note, as neither covariate shows an association with the risk of death (this may not remain the case in a more complete, fully-adjusted model). But let’s push ahead anyway and use <code>cox.zph()</code> to test the model fit and plot the results in evaluating proportional hazards for each of our covariates.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>(sch_res <span class="ot">&lt;-</span>  <span class="fu">cox.zph</span>(vfit1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       chisq df     p
trt     3.67  1 0.055
age     1.68  1 0.195
GLOBAL  6.20  2 0.045</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb6-2"><a href="#cb6-2"></a><span class="fu">plot</span>(sch_res[<span class="dv">1</span>], <span class="at">hr =</span> T) <span class="co"># trt</span></span>
<span id="cb6-3"><a href="#cb6-3"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb6-4"><a href="#cb6-4"></a><span class="fu">plot</span>(sch_res[<span class="dv">2</span>], <span class="at">hr =</span> T) <span class="co"># age</span></span>
<span id="cb6-5"><a href="#cb6-5"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>The hypothesis test for a horizontal line fitted through the residuals for each covariate reveals a non-significant p value for both <code>trt</code> and <code>age</code>, although we would have good justification for doubting the validity of a constant HR for <code>trt</code>. Further evidence for this is provided in the plots - while the smoother is fairly horizontal for <code>age</code>, it is not for <code>trt</code>, which demonstrates an increase in the HR early on followed by a gradual decline after the first or so.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note the red dashed line is meant simply as a reference constant null effect (HR = 1). The hypothesis test is a test against a constant HR (of any value).</p>
</div>
</div>
</section>
<section id="graphical-assessment." class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="graphical-assessment."><span class="header-section-number">4.2</span> Graphical assessment.</h2>
<p>This option involves plotting what are referred to as log-log survival curves over the different levels of the covariate. Essentially we take the log of the survival function twice and plot that resulting function. Note that “log-log” is technically -log(-log survival) which is equivalent to -log(cumulative hazard), so we are really plotting a version of the cumulative hazards, but we won’t dwell on the detail. The important point is that if hazards are proportional we expect these lines to be approximately parallel and be separated by a constant value of <span class="math inline">\(\beta\)</span> (i.e.&nbsp;the log HR) over the duration of observation time.</p>
<p>We can do this in <code>R</code> for the <code>trt</code> variable using the code shown below.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">plot</span>(<span class="fu">survfit</span>(<span class="fu">Surv</span>(vdata1<span class="sc">$</span>time, vdata1<span class="sc">$</span>status) <span class="sc">~</span> vdata1<span class="sc">$</span>trt), </span>
<span id="cb7-2"><a href="#cb7-2"></a>     <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"red"</span>), <span class="at">fun =</span> <span class="st">"cloglog"</span>, <span class="at">xlab =</span> <span class="st">"log time"</span>, <span class="at">ylab =</span> <span class="st">"log-log survival"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>An issue with graphical assessment of proportional hazards is that it is somewhat subjective and we don’t have a clear way to determine a significant violation. In this plot, however, I think the result is quite clear and we can assert with reasonable confidence that the HR for <code>trt</code> may not in fact be constant in time.</p>
</section>
<section id="time-dependent-variables." class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="time-dependent-variables."><span class="header-section-number">4.3</span> Time-dependent variables.</h2>
<p>The last approach to testing for proportional hazards on a covariate is to create an interaction between the covariate and time (or some function of it). This allows the ‘effect’ of the covariate to vary at different times and we can assess the proportional hazards assumption by testing for the significance of this interaction term. If the p value is statistically significant this provides some evidence for a time-varying ‘effect’ of the covariate on survival times (i.e.&nbsp;the HR is NOT constant over time).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The use and interpretation of such an interaction in a Cox model is really no different to that in any model - the main difference is that in this context we are interacting a covariate with time instead of another covariate. Keep in mind of course, that it is possible to include standard covariate-covariate interactions in the Cox model as well.</p>
</div>
</div>
<p>So, how do we specify this time-covariate interaction term in our Cox model?</p>
<p>Well there is a trick to this that relies on first knowing two small pieces of very important information, without which you will fall victim to the same naive error that has plagued countless analysts before you.</p>
<section id="one-simple-rule-about-covariate-values-in-the-cox-model" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="one-simple-rule-about-covariate-values-in-the-cox-model"><span class="header-section-number">4.3.1</span> One simple rule about covariate values in the Cox model</h3>
<p><strong>“You cannot look into the future”</strong></p>
<p>Terry Therneau - one of the main authors of the <code>survival</code> package, writes on page 2 of the package’s <a href="https://cran.r-project.org/web/packages/survival/vignettes/timedep.pdf">time-dependent vignette</a>:</p>
<p>“<strong>The key rule for time dependent covariates in a Cox model is simple and essentially the same as that for gambling: you cannot look into the future. A covariate may change in any way based on past data or outcomes, but it may not reach forward in time.</strong>”</p>
<p>And on page 101 of <a href="https://xsliulab.github.io/Workshop/2021/week3/survival-analysis-book.pdf">Applied Survival Analysis Using R</a>:</p>
<p>“The partial likelihood theory for survival data, introduced in Chap. 5, allows one to model survival times while accommodating covariate information. An important caveat to this theory is that the values of the covariates must be determined at time t = 0, when the patient enters the study, and remain constant thereafter. <strong>This issue arises with survival data because such data evolve over time, and it would be improper to use the value a covariate to model survival information that is observed before the covariate’s value is known.</strong> To accommodate covariates that may change their value over time (“time dependent covariates”), special measures are necessary to obtain valid parameter estimates. An intervention that occurs after the start of the trial, or a covariate (such as air pollution exposure) that changes values over the course of the study are two examples of time dependent variables.</p>
<p>The rule is clear: we cannot predict survival using covariate values from the future.”</p>
<p>And from <a href="https://pubmed.ncbi.nlm.nih.gov/8546126/">Logical and statistical fallacies in the use of Cox regression models</a>:</p>
<p>“A potential source of error involving the use of future information arises from the improper use of covariates in the Cox model…</p>
<p>…For example, we discuss why one should almost never use a covariate that has been averaged over a patient’s entire follow-up time as a baseline covariate. Instead, the baseline value should be used as a covariate, or the cumulative average up to each point in time should be used as a time-dependent covariate.”</p>
<p>You may wonder why I am telling you this? The reason is that I think it’s a common error for the naive analyst to use future covariate information in survival models. It is particularly salient to be aware of this when we are now talking about constructing a covariate-time interaction term. Because if I asked you how you would do this, I bet you a million dollars you would tell me something like “Well, I’ll just interact each persons event/censoring time with the covariate we want to test”. In formula terms:</p>
<p><code>vfit1 &lt;- coxph(Surv(time, status) ~ trt + age + trt:time, vdata1)</code></p>
<p>Well you would be wrong, because in doing this, you are breaking that cardinal rule of not looking into the future (I’ll show you why shortly).</p>
<p>With regards to this erroneous model specification, Terry Therneau writes on page 21 of the <a href="https://cran.r-project.org/web/packages/survival/vignettes/timedep.pdf">time-dependent vignette</a>:</p>
<p>“This mistake has been made often enough the the coxph routine has been updated to print an error message for such attempts. The issue is that the above code does not actually create a time dependent covariate, rather it creates a time-static value for each subject based on their value for the covariate time; no differently than if we had constructed the variable outside of a coxph call. <strong>This variable most definitely breaks the rule about not looking into the future, and one would quickly find the circularity: large values of time appear to predict long survival because long survival leads to large values for time.</strong>”</p>
</section>
<section id="event-times-are-all-important-in-the-cox-model" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="event-times-are-all-important-in-the-cox-model"><span class="header-section-number">4.3.2</span> Event times are all-important in the Cox model</h3>
<p>The second concept that you may have come across in your readings on survival analysis (but I would bet you probably don’t remember) is that event times are where the action is at in estimating the Cox model. <strong>At each event time the covariate values for the individual experiencing the event are compared against the values in place for all the individuals at risk at that time (i.e.&nbsp;in the “risk set”).</strong> Not in the past, and certainly not in the future, <strong>but at that time</strong>. Regression coefficients (i.e.&nbsp;log HRs) are then estimated as a function of these covariate values.</p>
</section>
<section id="putting-it-all-together" class="level3" data-number="4.3.3">
<h3 data-number="4.3.3" class="anchored" data-anchor-id="putting-it-all-together"><span class="header-section-number">4.3.3</span> Putting it all together</h3>
<p>So, now that we know the rule about not using future covariate information and also the importance of event times in Cox model estimation, how do we use this information to construct the <em>correct</em> time-covariate interaction we alluded to above in assessing the validity of proportional hazards?</p>
<p>The “trick” is to split our data at every event time. In doing this we create a new dataset where we essentially have multi-row (counting process) data for each person. Each person’s observation time is split into periods defined by <strong>all</strong> event times, for whatever time that person remains under observation. As an example, let’s look at just the first <code>3</code> patients in the <code>veteran</code> dataset:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="co"># Create new df with just the first 3 subjects</span></span>
<span id="cb8-2"><a href="#cb8-2"></a>vdata1_first3 <span class="ot">&lt;-</span>  vdata1 <span class="sc">|&gt;</span> </span>
<span id="cb8-3"><a href="#cb8-3"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) </span>
<span id="cb8-4"><a href="#cb8-4"></a>vdata1_first3 <span class="sc">|&gt;</span> </span>
<span id="cb8-5"><a href="#cb8-5"></a>  <span class="fu">kable</span>(<span class="at">align =</span> <span class="st">"c"</span>, <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">id</th>
<th style="text-align: center;">time</th>
<th style="text-align: center;">status</th>
<th style="text-align: center;">trt</th>
<th style="text-align: center;">age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">72</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">69</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">411</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">64</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">228</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">38</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Each of these patients experiences the event. We can use the <code>survSplit()</code> function to split each persons observation time by all events. When we do this we get:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="co"># Split time at every event and create vector of unique event times</span></span>
<span id="cb9-2"><a href="#cb9-2"></a>event_times <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">unique</span>(<span class="fu">with</span>(vdata1_first3, time[status <span class="sc">==</span> <span class="dv">1</span>])))</span>
<span id="cb9-3"><a href="#cb9-3"></a><span class="co"># Create new df in CP form with splits at every event time</span></span>
<span id="cb9-4"><a href="#cb9-4"></a>vdata2_first3 <span class="ot">&lt;-</span> <span class="fu">survSplit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span>., vdata1_first3, <span class="at">cut =</span> event_times)</span>
<span id="cb9-5"><a href="#cb9-5"></a>vdata2_first3 <span class="sc">|&gt;</span> </span>
<span id="cb9-6"><a href="#cb9-6"></a>  <span class="fu">kable</span>(<span class="at">align =</span> <span class="st">"c"</span>, <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">id</th>
<th style="text-align: center;">trt</th>
<th style="text-align: center;">age</th>
<th style="text-align: center;">tstart</th>
<th style="text-align: center;">time</th>
<th style="text-align: center;">status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">69</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">72</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">64</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">72</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">64</td>
<td style="text-align: center;">72</td>
<td style="text-align: center;">228</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">64</td>
<td style="text-align: center;">228</td>
<td style="text-align: center;">411</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">72</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">72</td>
<td style="text-align: center;">228</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>You can see that Subject <code>1</code> has the shortest observation time (<code>72</code> days) and given there were no other event times in that period, their data remains the same. Subject <code>2</code>, however, has the longest observation time (<code>411</code> days) and given there are <code>3</code> events and they are at in the <em>risk set</em> for all of those, their observation time is split into <code>3</code> periods defined by those event timings. Subject <code>3</code> has an observation time of <code>228</code> days and as they are only at risk therefore for two of the three events, their observation time is split into <code>2</code> periods. And so on - hopefully you are starting to get the picture.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>One issue to be aware of with splitting time at every event is that it can lead to some very large datasets!</p>
</div>
</div>
<p>In this data manipulation trick we are emulating single-row/person data with multi-row/person data, but the specifications are equivalent as the covariate values remain the same for each individual. The point is that we now have a data set where the risk sets used to calculate the covariate-time interaction respect the <em>current</em> time, not a potentially future time defined by the end of observation (i.e.&nbsp;event/censoring) as we would have used in the naive analysis.</p>
<p>After all of that, let’s finally run this model. We take our <code>137</code> patients and use <code>survSplit</code> to create an expanded dataset whereby observation time for each patient is split at all death times. We then use a <code>trt:time</code> interaction to assess whether proportional hazards may hold over the duration of observation.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="co"># Split time at every event and create vector of unique event times</span></span>
<span id="cb10-2"><a href="#cb10-2"></a>event_times <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">unique</span>(<span class="fu">with</span>(vdata1, time[status <span class="sc">==</span> <span class="dv">1</span>])))</span>
<span id="cb10-3"><a href="#cb10-3"></a><span class="co"># Create new df in CP form with splits at every event time</span></span>
<span id="cb10-4"><a href="#cb10-4"></a>vdata2 <span class="ot">&lt;-</span> <span class="fu">survSplit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span>., vdata1, <span class="at">cut =</span> event_times)</span>
<span id="cb10-5"><a href="#cb10-5"></a>vfit2 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(tstart, time, status) <span class="sc">~</span> trt <span class="sc">+</span> age <span class="sc">+</span> trt<span class="sc">:</span>time, vdata2)</span>
<span id="cb10-6"><a href="#cb10-6"></a><span class="fu">tbl_regression</span>(vfit2, <span class="at">exp =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="hakajpipra" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#hakajpipra table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#hakajpipra thead, #hakajpipra tbody, #hakajpipra tfoot, #hakajpipra tr, #hakajpipra td, #hakajpipra th {
  border-style: none;
}

#hakajpipra p {
  margin: 0;
  padding: 0;
}

#hakajpipra .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#hakajpipra .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#hakajpipra .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hakajpipra .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hakajpipra .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hakajpipra .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hakajpipra .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hakajpipra .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hakajpipra .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hakajpipra .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hakajpipra .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hakajpipra .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hakajpipra .gt_spanner_row {
  border-bottom-style: hidden;
}

#hakajpipra .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#hakajpipra .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hakajpipra .gt_from_md > :first-child {
  margin-top: 0;
}

#hakajpipra .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hakajpipra .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hakajpipra .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#hakajpipra .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#hakajpipra .gt_row_group_first td {
  border-top-width: 2px;
}

#hakajpipra .gt_row_group_first th {
  border-top-width: 2px;
}

#hakajpipra .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hakajpipra .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#hakajpipra .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#hakajpipra .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hakajpipra .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hakajpipra .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hakajpipra .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#hakajpipra .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hakajpipra .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hakajpipra .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hakajpipra .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hakajpipra .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hakajpipra .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hakajpipra .gt_left {
  text-align: left;
}

#hakajpipra .gt_center {
  text-align: center;
}

#hakajpipra .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hakajpipra .gt_font_normal {
  font-weight: normal;
}

#hakajpipra .gt_font_bold {
  font-weight: bold;
}

#hakajpipra .gt_font_italic {
  font-style: italic;
}

#hakajpipra .gt_super {
  font-size: 65%;
}

#hakajpipra .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#hakajpipra .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#hakajpipra .gt_indent_1 {
  text-indent: 5px;
}

#hakajpipra .gt_indent_2 {
  text-indent: 10px;
}

#hakajpipra .gt_indent_3 {
  text-indent: 15px;
}

#hakajpipra .gt_indent_4 {
  text-indent: 20px;
}

#hakajpipra .gt_indent_5 {
  text-indent: 25px;
}
</style>

<table class="gt_table table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="header gt_col_headings">
<th id="<strong>Characteristic</strong>" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="<strong>HR</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>HR</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
<th id="<strong>95% CI</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
<th id="<strong>p-value</strong>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">trt</td>
<td class="gt_row gt_center" headers="estimate">1.43</td>
<td class="gt_row gt_center" headers="ci">0.88, 2.33</td>
<td class="gt_row gt_center" headers="p.value">0.15</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">age</td>
<td class="gt_row gt_center" headers="estimate">1.01</td>
<td class="gt_row gt_center" headers="ci">0.99, 1.03</td>
<td class="gt_row gt_center" headers="p.value">0.4</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">trt * time</td>
<td class="gt_row gt_center" headers="estimate">1.00</td>
<td class="gt_row gt_center" headers="ci">0.99, 1.00</td>
<td class="gt_row gt_center" headers="p.value">0.030</td>
</tr>
</tbody><tfoot class="gt_footnotes">
<tr class="even">
<td colspan="4" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> HR = Hazard Ratio, CI = Confidence Interval</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
<p>The p value for the interaction term is <code>0.03</code> and so by this third method we may also surmise that the hazards for <code>trt</code> may not be proportional over time.</p>
<p>Out of interest - what would we have gotten in the naive analysis - i.e.&nbsp;where we create the interaction term using the event/censoring time?</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="co"># Naive model using final observation time</span></span>
<span id="cb11-2"><a href="#cb11-2"></a>vfit3 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> trt <span class="sc">+</span> age <span class="sc">+</span> trt<span class="sc">:</span>time, vdata1)</span>
<span id="cb11-3"><a href="#cb11-3"></a><span class="fu">tbl_regression</span>(vfit3, <span class="at">exp =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="kqthrxvqxz" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#kqthrxvqxz table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#kqthrxvqxz thead, #kqthrxvqxz tbody, #kqthrxvqxz tfoot, #kqthrxvqxz tr, #kqthrxvqxz td, #kqthrxvqxz th {
  border-style: none;
}

#kqthrxvqxz p {
  margin: 0;
  padding: 0;
}

#kqthrxvqxz .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#kqthrxvqxz .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#kqthrxvqxz .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#kqthrxvqxz .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#kqthrxvqxz .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#kqthrxvqxz .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kqthrxvqxz .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#kqthrxvqxz .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#kqthrxvqxz .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#kqthrxvqxz .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#kqthrxvqxz .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#kqthrxvqxz .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#kqthrxvqxz .gt_spanner_row {
  border-bottom-style: hidden;
}

#kqthrxvqxz .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#kqthrxvqxz .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#kqthrxvqxz .gt_from_md > :first-child {
  margin-top: 0;
}

#kqthrxvqxz .gt_from_md > :last-child {
  margin-bottom: 0;
}

#kqthrxvqxz .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#kqthrxvqxz .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#kqthrxvqxz .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#kqthrxvqxz .gt_row_group_first td {
  border-top-width: 2px;
}

#kqthrxvqxz .gt_row_group_first th {
  border-top-width: 2px;
}

#kqthrxvqxz .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#kqthrxvqxz .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#kqthrxvqxz .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#kqthrxvqxz .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kqthrxvqxz .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#kqthrxvqxz .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#kqthrxvqxz .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#kqthrxvqxz .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#kqthrxvqxz .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kqthrxvqxz .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#kqthrxvqxz .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#kqthrxvqxz .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#kqthrxvqxz .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#kqthrxvqxz .gt_left {
  text-align: left;
}

#kqthrxvqxz .gt_center {
  text-align: center;
}

#kqthrxvqxz .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#kqthrxvqxz .gt_font_normal {
  font-weight: normal;
}

#kqthrxvqxz .gt_font_bold {
  font-weight: bold;
}

#kqthrxvqxz .gt_font_italic {
  font-style: italic;
}

#kqthrxvqxz .gt_super {
  font-size: 65%;
}

#kqthrxvqxz .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#kqthrxvqxz .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#kqthrxvqxz .gt_indent_1 {
  text-indent: 5px;
}

#kqthrxvqxz .gt_indent_2 {
  text-indent: 10px;
}

#kqthrxvqxz .gt_indent_3 {
  text-indent: 15px;
}

#kqthrxvqxz .gt_indent_4 {
  text-indent: 20px;
}

#kqthrxvqxz .gt_indent_5 {
  text-indent: 25px;
}
</style>

<table class="gt_table table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="header gt_col_headings">
<th id="<strong>Characteristic</strong>" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="<strong>HR</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>HR</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
<th id="<strong>95% CI</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
<th id="<strong>p-value</strong>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">trt</td>
<td class="gt_row gt_center" headers="estimate">8.06</td>
<td class="gt_row gt_center" headers="ci">4.37, 14.9</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">age</td>
<td class="gt_row gt_center" headers="estimate">1.01</td>
<td class="gt_row gt_center" headers="ci">0.99, 1.03</td>
<td class="gt_row gt_center" headers="p.value">0.4</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">trt * time</td>
<td class="gt_row gt_center" headers="estimate">0.99</td>
<td class="gt_row gt_center" headers="ci">0.98, 0.99</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
</tbody><tfoot class="gt_footnotes">
<tr class="even">
<td colspan="4" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> HR = Hazard Ratio, CI = Confidence Interval</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
<p>Hmmm - quite different… and quite wrong!</p>
<p>There is actually a quicker way to run this equivalent model without needing to first split the data, but I wanted to show you the “first-principles” approach, first. Again, on page 21 of the <a href="https://cran.r-project.org/web/packages/survival/vignettes/timedep.pdf">time-dependent vignette</a>, a general method is outlined which relies on the <em>time-transform</em> functionality of <code>coxph()</code>. Using this model specification, you will see that we end up with the same result.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>vfit3 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> trt <span class="sc">+</span> age <span class="sc">+</span> <span class="fu">tt</span>(trt), <span class="at">tt =</span> <span class="cf">function</span>(x,t,...) x<span class="sc">*</span>t, vdata1)</span>
<span id="cb12-2"><a href="#cb12-2"></a><span class="fu">tbl_regression</span>(vfit3, <span class="at">exp =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="cskngfhvac" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#cskngfhvac table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#cskngfhvac thead, #cskngfhvac tbody, #cskngfhvac tfoot, #cskngfhvac tr, #cskngfhvac td, #cskngfhvac th {
  border-style: none;
}

#cskngfhvac p {
  margin: 0;
  padding: 0;
}

#cskngfhvac .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#cskngfhvac .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#cskngfhvac .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#cskngfhvac .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#cskngfhvac .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cskngfhvac .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cskngfhvac .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cskngfhvac .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#cskngfhvac .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#cskngfhvac .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#cskngfhvac .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#cskngfhvac .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#cskngfhvac .gt_spanner_row {
  border-bottom-style: hidden;
}

#cskngfhvac .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#cskngfhvac .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#cskngfhvac .gt_from_md > :first-child {
  margin-top: 0;
}

#cskngfhvac .gt_from_md > :last-child {
  margin-bottom: 0;
}

#cskngfhvac .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#cskngfhvac .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#cskngfhvac .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#cskngfhvac .gt_row_group_first td {
  border-top-width: 2px;
}

#cskngfhvac .gt_row_group_first th {
  border-top-width: 2px;
}

#cskngfhvac .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cskngfhvac .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#cskngfhvac .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#cskngfhvac .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cskngfhvac .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cskngfhvac .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#cskngfhvac .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#cskngfhvac .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#cskngfhvac .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cskngfhvac .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cskngfhvac .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cskngfhvac .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cskngfhvac .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cskngfhvac .gt_left {
  text-align: left;
}

#cskngfhvac .gt_center {
  text-align: center;
}

#cskngfhvac .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#cskngfhvac .gt_font_normal {
  font-weight: normal;
}

#cskngfhvac .gt_font_bold {
  font-weight: bold;
}

#cskngfhvac .gt_font_italic {
  font-style: italic;
}

#cskngfhvac .gt_super {
  font-size: 65%;
}

#cskngfhvac .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#cskngfhvac .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#cskngfhvac .gt_indent_1 {
  text-indent: 5px;
}

#cskngfhvac .gt_indent_2 {
  text-indent: 10px;
}

#cskngfhvac .gt_indent_3 {
  text-indent: 15px;
}

#cskngfhvac .gt_indent_4 {
  text-indent: 20px;
}

#cskngfhvac .gt_indent_5 {
  text-indent: 25px;
}
</style>

<table class="gt_table table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="header gt_col_headings">
<th id="<strong>Characteristic</strong>" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="<strong>HR</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>HR</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
<th id="<strong>95% CI</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
<th id="<strong>p-value</strong>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">trt</td>
<td class="gt_row gt_center" headers="estimate">1.43</td>
<td class="gt_row gt_center" headers="ci">0.88, 2.33</td>
<td class="gt_row gt_center" headers="p.value">0.15</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">age</td>
<td class="gt_row gt_center" headers="estimate">1.01</td>
<td class="gt_row gt_center" headers="ci">0.99, 1.03</td>
<td class="gt_row gt_center" headers="p.value">0.4</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">tt(trt)</td>
<td class="gt_row gt_center" headers="estimate">1.00</td>
<td class="gt_row gt_center" headers="ci">0.99, 1.00</td>
<td class="gt_row gt_center" headers="p.value">0.030</td>
</tr>
</tbody><tfoot class="gt_footnotes">
<tr class="even">
<td colspan="4" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> HR = Hazard Ratio, CI = Confidence Interval</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
</section>
</section>
</section>
<section id="wrap-up" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Wrap-Up</h1>
<p>I had originally intended to make this all one post, but clearly I have gone on for too long as usual. Today we have discussed how to diagnose non-proportional hazards, but of course you are wondering about the equally important question of “what do we actually do about non-proportional hazards?”</p>
<p>I will tackle that in the Part 2 post in a few weeks, so I hope to see you then.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="pgseye/Weekly_Stats_Tips" data-repo-id="R_kgDOKvfOfQ" data-category="General" data-category-id="DIC_kwDOKvfOfc4CbFWq" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark"><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb13" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb13-1"><a href="#cb13-1"></a><span class="co">---</span></span>
<span id="cb13-2"><a href="#cb13-2"></a><span class="an">title:</span><span class="co"> "Are your Hazards Proportional? - What to do when it just ain't so (Part 1)"</span></span>
<span id="cb13-3"><a href="#cb13-3"></a><span class="an">date:</span><span class="co"> 2025-06-27</span></span>
<span id="cb13-4"><a href="#cb13-4"></a><span class="an">categories:</span><span class="co"> [code, concept, modelling, visualisation]</span></span>
<span id="cb13-5"><a href="#cb13-5"></a><span class="co"># image: "images/plot.png"</span></span>
<span id="cb13-6"><a href="#cb13-6"></a><span class="an">description:</span><span class="co"> "The hazards of misunderstanding the hazard ratio."</span></span>
<span id="cb13-7"><a href="#cb13-7"></a><span class="co">---</span></span>
<span id="cb13-8"><a href="#cb13-8"></a></span>
<span id="cb13-9"><a href="#cb13-9"></a><span class="fu"># Background</span></span>
<span id="cb13-10"><a href="#cb13-10"></a></span>
<span id="cb13-11"><a href="#cb13-11"></a>Ok, I'm going to be a bit melodramatic here, but bear with me. Have you ever felt like crying when your carefully constructed Cox model - one that is giving you the significant 'effect/s' you've been dreaming of - fails at the last hurdle when you discover that one (or more) of its covariates violates the assumption of proportional hazards?</span>
<span id="cb13-12"><a href="#cb13-12"></a></span>
<span id="cb13-13"><a href="#cb13-13"></a>Or is that just me?</span>
<span id="cb13-14"><a href="#cb13-14"></a></span>
<span id="cb13-15"><a href="#cb13-15"></a>The Cox model is ubiquitous in medical research and is typically utilised when questions develop around assessing the time to some outcome of interest. Like any other mathematical model, the Cox model is capable of capturing only a simple reflection of biological systems that are much more complex in reality. To that end assumptions are made about the nature of the data that the model is expected to parse, and the greater the violation of those assumptions, the less faithful one can expect the reflection to be. In other words, the model becomes less and less trustworthy.</span>
<span id="cb13-16"><a href="#cb13-16"></a></span>
<span id="cb13-17"><a href="#cb13-17"></a>Where am I headed with my ham-fisted attempt at philosophising? Well, as I'm sure you know, one of the primary assumptions underpinning the Cox model is that of proportional hazards. I have actually discussed this in one of my <span class="co">[</span><span class="ot">previous posts on survival analysis</span><span class="co">](https://msni-stats-tips.netlify.app/posts/021_01nov_2024/#semi-parametric-cox-model)</span> when I introduced the Cox model, but it's so important I'm going to reiterate here.</span>
<span id="cb13-18"><a href="#cb13-18"></a></span>
<span id="cb13-19"><a href="#cb13-19"></a><span class="fu"># Proportional Hazards (in a Nutshell)</span></span>
<span id="cb13-20"><a href="#cb13-20"></a></span>
<span id="cb13-21"><a href="#cb13-21"></a>The following is what I said in that post:</span>
<span id="cb13-22"><a href="#cb13-22"></a></span>
<span id="cb13-23"><a href="#cb13-23"></a>"The proportional hazards assumption basically requires that the hazard ratio (HR) is constant over time, or equivalently, that the hazard for one individual is proportional to the hazard for any other individual, and where the proportionality constant doesn't depend on time.</span>
<span id="cb13-24"><a href="#cb13-24"></a></span>
<span id="cb13-25"><a href="#cb13-25"></a>So if we look at the figure below - I have plotted hypothetical hazard functions for males (in blue) and females (in red) for the risk of some event. You'll note that the shapes are essentially the same but are scaled versions of one another. When proportional hazards hold, then we can take a ratio of the two hazard rates at any time point and that ratio should remain constant. And I've illustrated that here at two time points - $t1$ and $t2$. The difference in the hazards obviously varies but the ratio of the hazards at those two time points is the same. At time <span class="in">`1`</span> a hazard rate of <span class="in">`3`</span> for males and <span class="in">`2`</span> for females gives a HR of <span class="in">`1.5`</span> and similarly, at time <span class="in">`2`</span>, a hazard rate of <span class="in">`0.75`</span> for males and <span class="in">`0.5`</span> for females, again gives a HR of <span class="in">`1.5`</span>.</span>
<span id="cb13-26"><a href="#cb13-26"></a></span>
<span id="cb13-27"><a href="#cb13-27"></a><span class="al">![](images/prop_hazards.png)</span>{fig-align="center"}</span>
<span id="cb13-28"><a href="#cb13-28"></a></span>
<span id="cb13-29"><a href="#cb13-29"></a>**In reality, hazard rates are probably not going to be exactly proportional the entire time, but the aim is to make sure any departures from proportionality are minimal - otherwise this means the HR itself varies with time and this adds further complexity to your model.**"</span>
<span id="cb13-30"><a href="#cb13-30"></a></span>
<span id="cb13-31"><a href="#cb13-31"></a>All of that remains true, but the last paragraph is particularly important in the context of this week's topic. In general, we just tend to assume the HR that is output by <span class="in">`coxph()`</span> is valid over the entire duration of observation when this is unlikely to be the case. If hazards are in fact non-proportional and we still accept that HR as the single 'effect' estimate, then it represents an **averaged HR** over the observation period (this <span class="co">[</span><span class="ot">paper</span><span class="co">](https://pmc.ncbi.nlm.nih.gov/articles/PMC3653612/)</span> discusses this issue - and more - in greater detail). Small departures from proportionality are probably still OK, but it's the larger departures that become more problematic in our model validity. The good news is there are steps we can take to test for these departures and that is ultimately the focus of today's post.</span>
<span id="cb13-32"><a href="#cb13-32"></a></span>
<span id="cb13-33"><a href="#cb13-33"></a><span class="fu"># tvc's vs tvc's</span></span>
<span id="cb13-34"><a href="#cb13-34"></a></span>
<span id="cb13-35"><a href="#cb13-35"></a>Before we go any further I think it is important to clarify a couple of related but distinct concepts regarding "time variation" in survival analyses, as "tvc" is an acronym with two different definitions depending on the context in which it is used.</span>
<span id="cb13-36"><a href="#cb13-36"></a></span>
<span id="cb13-37"><a href="#cb13-37"></a><span class="fu">## tvc (time-varying covariate)</span></span>
<span id="cb13-38"><a href="#cb13-38"></a></span>
<span id="cb13-39"><a href="#cb13-39"></a>In perhaps the more common usage, "tvc" can represent a *time-varying covariate* (also known as time-dependent covariate (tdc)). This is a covariate whose *values change* over the duration of one's observation period, but whose *'effect' on survival typically remains constant.* A good example here would be different time periods in which a person received treatment or not. Time-varying covariates are constructed as multi-row (i.e. [counting process](https://msni-stats-tips.netlify.app/posts/006_23feb_2024/#correct-analysis-assuming-treatment-status-is-time-varying)) data where each row contains a non-overlapping time period defined by a different treatment covariate value. Proportional hazards may still be assessed with counting process data and if no violation is noted, **a constant HR over the duration of observation** may be assumed.</span>
<span id="cb13-40"><a href="#cb13-40"></a></span>
<span id="cb13-41"><a href="#cb13-41"></a><span class="fu">## tvc (time-varying coefficient)</span></span>
<span id="cb13-42"><a href="#cb13-42"></a></span>
<span id="cb13-43"><a href="#cb13-43"></a>Now, without intending to create confusion, "tvc" may also represent a *time-varying coefficient* (also known as time-dependent coefficient (tdc)). This is associated with a covariate whose baseline *values remain constant* over the duration of observation, but whose *'effect' on the risk of an event can indeed change with time.* **In other words, the HR varies with time.** Data are typically formatted as one-row per person.</span>
<span id="cb13-44"><a href="#cb13-44"></a></span>
<span id="cb13-45"><a href="#cb13-45"></a><span class="fu">## Well is it tvc or tvc?</span></span>
<span id="cb13-46"><a href="#cb13-46"></a></span>
<span id="cb13-47"><a href="#cb13-47"></a>In a survival analysis, one may have:</span>
<span id="cb13-48"><a href="#cb13-48"></a></span>
<span id="cb13-49"><a href="#cb13-49"></a><span class="ss">1.  </span>Neither time-varying covariates nor time-varying coefficients (single-row/person, constant HR).</span>
<span id="cb13-50"><a href="#cb13-50"></a></span>
<span id="cb13-51"><a href="#cb13-51"></a><span class="ss">2.  </span>Time-varying coefficients but not time-varying covariates (single-row/person, time-varying HR).</span>
<span id="cb13-52"><a href="#cb13-52"></a></span>
<span id="cb13-53"><a href="#cb13-53"></a><span class="ss">3.  </span>Time-varying covariates but not time-varying coefficients (multi-row/person, constant HR).</span>
<span id="cb13-54"><a href="#cb13-54"></a></span>
<span id="cb13-55"><a href="#cb13-55"></a><span class="ss">4.  </span>Time-varying coefficients and time-varying covariates (multi-row/person, time-varying HR).</span>
<span id="cb13-56"><a href="#cb13-56"></a></span>
<span id="cb13-57"><a href="#cb13-57"></a>In today's post, the examples and discussion I provide will only focus on scenario 2. The addition of time-varying covariates into analyses with time-varying coefficients (scenario 4) complicates matters significantly and I've made the decision not to tackle this for the time being (although I may come back to this in a later post).</span>
<span id="cb13-58"><a href="#cb13-58"></a></span>
<span id="cb13-59"><a href="#cb13-59"></a>But now that we've cleared that up, let's get back to the issue at hand.</span>
<span id="cb13-60"><a href="#cb13-60"></a></span>
<span id="cb13-61"><a href="#cb13-61"></a><span class="fu"># Testing for Proportional Hazards</span></span>
<span id="cb13-62"><a href="#cb13-62"></a></span>
<span id="cb13-63"><a href="#cb13-63"></a>There are essentially three approaches to testing the proportional hazards assumption, although dare I say most of us probably only ever use the first.</span>
<span id="cb13-64"><a href="#cb13-64"></a></span>
<span id="cb13-65"><a href="#cb13-65"></a><span class="ss">1.  </span>Goodness of Fit (GOF) tests.</span>
<span id="cb13-66"><a href="#cb13-66"></a><span class="ss">2.  </span>Graphical assessment.</span>
<span id="cb13-67"><a href="#cb13-67"></a><span class="ss">3.  </span>Time-dependent variables.</span>
<span id="cb13-68"><a href="#cb13-68"></a></span>
<span id="cb13-69"><a href="#cb13-69"></a>To illustrate these approaches we'll use the <span class="in">`veteran`</span> dataset that is built into <span class="in">`R`</span>'s <span class="in">`survival`</span> package. Details can be found <span class="co">[</span><span class="ot">here</span><span class="co">](https://www.rdocumentation.org/packages/survival/versions/3.8-3/topics/veteran)</span> but, in brief, the data consist of survival times for <span class="in">`137`</span> lung-cancer sufferers enrolled in an RCT of two treatment regimens. The variables of interest for the purpose of today's exercise are:</span>
<span id="cb13-70"><a href="#cb13-70"></a></span>
<span id="cb13-71"><a href="#cb13-71"></a><span class="ss">-   </span><span class="in">`time`</span> - survival time (days)</span>
<span id="cb13-72"><a href="#cb13-72"></a></span>
<span id="cb13-73"><a href="#cb13-73"></a><span class="ss">-   </span><span class="in">`status`</span> - censor (0), death (1)</span>
<span id="cb13-74"><a href="#cb13-74"></a></span>
<span id="cb13-75"><a href="#cb13-75"></a><span class="ss">-   </span><span class="in">`trt`</span> - treatment <span class="sc">\[</span>standard (1) vs test (2)<span class="sc">\]</span></span>
<span id="cb13-76"><a href="#cb13-76"></a></span>
<span id="cb13-77"><a href="#cb13-77"></a><span class="ss">-   </span><span class="in">`age`</span> - age (yrs)</span>
<span id="cb13-78"><a href="#cb13-78"></a></span>
<span id="cb13-79"><a href="#cb13-79"></a>We'll consider <span class="in">`trt`</span> our primary "exposure" of interest and <span class="in">`age`</span> a covariate to adjust for. The first few rows of the data look like:</span>
<span id="cb13-80"><a href="#cb13-80"></a></span>
<span id="cb13-83"><a href="#cb13-83"></a><span class="in">```{r}</span></span>
<span id="cb13-84"><a href="#cb13-84"></a><span class="co">#| message: false</span></span>
<span id="cb13-85"><a href="#cb13-85"></a><span class="co">#| warning: false</span></span>
<span id="cb13-86"><a href="#cb13-86"></a><span class="fu">library</span>(survival)</span>
<span id="cb13-87"><a href="#cb13-87"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb13-88"><a href="#cb13-88"></a><span class="fu">library</span>(survminer)</span>
<span id="cb13-89"><a href="#cb13-89"></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb13-90"><a href="#cb13-90"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb13-91"><a href="#cb13-91"></a><span class="co"># Load veteran data from survival package</span></span>
<span id="cb13-92"><a href="#cb13-92"></a>vdata1 <span class="ot">&lt;-</span>  veteran</span>
<span id="cb13-93"><a href="#cb13-93"></a><span class="co"># Make treatment variable equal to 0,1 instead of 1,2 (not necessary, but I just like to work with the former)</span></span>
<span id="cb13-94"><a href="#cb13-94"></a>vdata1<span class="sc">$</span>trt <span class="ot">&lt;-</span>  <span class="fu">as.numeric</span>(vdata1<span class="sc">$</span>trt) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb13-95"><a href="#cb13-95"></a><span class="co"># Create id variable and organise columns</span></span>
<span id="cb13-96"><a href="#cb13-96"></a>vdata1<span class="sc">$</span>id <span class="ot">&lt;-</span>  <span class="fu">seq</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">dim</span>(vdata1)[<span class="dv">1</span>])</span>
<span id="cb13-97"><a href="#cb13-97"></a>vdata1 <span class="ot">&lt;-</span>  vdata1 <span class="sc">|&gt;</span> </span>
<span id="cb13-98"><a href="#cb13-98"></a>  <span class="fu">select</span>(id, time, status, trt, age)</span>
<span id="cb13-99"><a href="#cb13-99"></a><span class="fu">head</span>(vdata1, <span class="dv">10</span>) <span class="sc">|&gt;</span> </span>
<span id="cb13-100"><a href="#cb13-100"></a>  <span class="fu">kable</span>(<span class="at">align =</span> <span class="st">"c"</span>, <span class="at">digits =</span> <span class="dv">2</span>)</span>
<span id="cb13-101"><a href="#cb13-101"></a><span class="in">```</span></span>
<span id="cb13-102"><a href="#cb13-102"></a></span>
<span id="cb13-103"><a href="#cb13-103"></a>&lt;br&gt;</span>
<span id="cb13-104"><a href="#cb13-104"></a></span>
<span id="cb13-105"><a href="#cb13-105"></a>As a precursor step let's plot the Kaplan-Meier curves for these data - for no other reason than to calibrate our expectations for the upcoming proportional hazards tests.</span>
<span id="cb13-106"><a href="#cb13-106"></a></span>
<span id="cb13-109"><a href="#cb13-109"></a><span class="in">```{r}</span></span>
<span id="cb13-110"><a href="#cb13-110"></a><span class="co"># Kaplan-Meier plot</span></span>
<span id="cb13-111"><a href="#cb13-111"></a>km_trt_fit <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> trt, <span class="at">data =</span> veteran)</span>
<span id="cb13-112"><a href="#cb13-112"></a><span class="fu">ggsurvplot</span>(km_trt_fit, <span class="at">data =</span> veteran, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">"#E7B800"</span>, <span class="st">"#2E9FDF"</span>), <span class="at">conf.int =</span> F,</span>
<span id="cb13-113"><a href="#cb13-113"></a>           <span class="at">legend.labs =</span> <span class="fu">c</span>(<span class="st">"standard"</span>, <span class="st">"test"</span>), <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">20</span>))</span>
<span id="cb13-114"><a href="#cb13-114"></a><span class="in">```</span></span>
<span id="cb13-115"><a href="#cb13-115"></a></span>
<span id="cb13-116"><a href="#cb13-116"></a>OK, well this is interesting as it already tells us we have a problem with the <span class="in">`trt`</span> variable. Survival curves should ideally gradually separate over time. When they appear to converge - or worse still **cross** - this should be a warning to us that the hazard function for one group is NOT a scaled function of the other (i.e. they are non-proportional with respect to time). While this is a fairly obvious violation in this example, it is not uncommon for non-proportionality to appear more subtle in KM plots leaving us unsure as to whether there may be a problem or not. Not to worry though - that's why we have these additional tests we can employ, and which I will discuss now!</span>
<span id="cb13-117"><a href="#cb13-117"></a></span>
<span id="cb13-118"><a href="#cb13-118"></a><span class="fu">## Goodness of Fit (GOF) tests.</span></span>
<span id="cb13-119"><a href="#cb13-119"></a></span>
<span id="cb13-120"><a href="#cb13-120"></a>The classic GOF approach uses a test statistic and p-value to assess the significance of the PH assumption based on the Schoenfeld residuals of the Cox model (I won't attempt to explain how these residuals are derived). Visually, if proportional hazards hold, then a plot of the scaled Schoenfeld residuals over time (for a particular covariate) should have zero slope. That is, we should ideally see a horizontal line which indicates that the residuals for that covariate are not related to survival time. In <span class="in">`R`</span> we can use the <span class="in">`cox.zph()`</span> function to perform a significance test for each covariate and for the model as a whole. Additionally, we can <span class="in">`plot()`</span> the object returned by the <span class="in">`cox.zph()`</span> call to visualise the shape of the resulting smoothed (loess) curve fitted to the residuals, for each covariate. **It can be very helpful to take note of this functional form as that is how the HR for the covariate is expected to actually vary over time.** This also provides a sanity check for any time-varying HR we might calculate later, if we decide to take remediation action in relaxing the assumption of proportionality in our model specification.</span>
<span id="cb13-121"><a href="#cb13-121"></a></span>
<span id="cb13-122"><a href="#cb13-122"></a>To test the proportional hazards assumption we first need to fit a Cox model, so let's do that now.</span>
<span id="cb13-123"><a href="#cb13-123"></a></span>
<span id="cb13-126"><a href="#cb13-126"></a><span class="in">```{r}</span></span>
<span id="cb13-127"><a href="#cb13-127"></a><span class="co"># Fit basic model with treatment and age as the only predictors</span></span>
<span id="cb13-128"><a href="#cb13-128"></a>vfit1 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> trt <span class="sc">+</span> age, vdata1)</span>
<span id="cb13-129"><a href="#cb13-129"></a><span class="fu">tbl_regression</span>(vfit1, <span class="at">exp =</span> T)</span>
<span id="cb13-130"><a href="#cb13-130"></a><span class="in">```</span></span>
<span id="cb13-131"><a href="#cb13-131"></a></span>
<span id="cb13-132"><a href="#cb13-132"></a>Based on these model results there does not appear to be much to note, as neither covariate shows an association with the risk of death (this may not remain the case in a more complete, fully-adjusted model). But let's push ahead anyway and use <span class="in">`cox.zph()`</span> to test the model fit and plot the results in evaluating proportional hazards for each of our covariates.</span>
<span id="cb13-133"><a href="#cb13-133"></a></span>
<span id="cb13-136"><a href="#cb13-136"></a><span class="in">```{r}</span></span>
<span id="cb13-137"><a href="#cb13-137"></a>(sch_res <span class="ot">&lt;-</span>  <span class="fu">cox.zph</span>(vfit1))</span>
<span id="cb13-138"><a href="#cb13-138"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb13-139"><a href="#cb13-139"></a><span class="fu">plot</span>(sch_res[<span class="dv">1</span>], <span class="at">hr =</span> T) <span class="co"># trt</span></span>
<span id="cb13-140"><a href="#cb13-140"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb13-141"><a href="#cb13-141"></a><span class="fu">plot</span>(sch_res[<span class="dv">2</span>], <span class="at">hr =</span> T) <span class="co"># age</span></span>
<span id="cb13-142"><a href="#cb13-142"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb13-143"><a href="#cb13-143"></a><span class="in">```</span></span>
<span id="cb13-144"><a href="#cb13-144"></a></span>
<span id="cb13-145"><a href="#cb13-145"></a>The hypothesis test for a horizontal line fitted through the residuals for each covariate reveals a non-significant p value for both <span class="in">`trt`</span> and <span class="in">`age`</span>, although we would have good justification for doubting the validity of a constant HR for <span class="in">`trt`</span>. Further evidence for this is provided in the plots - while the smoother is fairly horizontal for <span class="in">`age`</span>, it is not for <span class="in">`trt`</span>, which demonstrates an increase in the HR early on followed by a gradual decline after the first or so.</span>
<span id="cb13-146"><a href="#cb13-146"></a></span>
<span id="cb13-147"><a href="#cb13-147"></a>::: callout-note</span>
<span id="cb13-148"><a href="#cb13-148"></a>Note the red dashed line is meant simply as a reference constant null effect (HR = 1). The hypothesis test is a test against a constant HR (of any value).</span>
<span id="cb13-149"><a href="#cb13-149"></a>:::</span>
<span id="cb13-150"><a href="#cb13-150"></a></span>
<span id="cb13-151"><a href="#cb13-151"></a><span class="fu">## Graphical assessment.</span></span>
<span id="cb13-152"><a href="#cb13-152"></a></span>
<span id="cb13-153"><a href="#cb13-153"></a>This option involves plotting what are referred to as log-log survival curves over the different levels of the covariate. Essentially we take the log of the survival function twice and plot that resulting function. Note that "log-log" is technically -log(-log survival) which is equivalent to -log(cumulative hazard), so we are really plotting a version of the cumulative hazards, but we won't dwell on the detail. The important point is that if hazards are proportional we expect these lines to be approximately parallel and be separated by a constant value of $\beta$ (i.e. the log HR) over the duration of observation time.</span>
<span id="cb13-154"><a href="#cb13-154"></a></span>
<span id="cb13-155"><a href="#cb13-155"></a>We can do this in <span class="in">`R`</span> for the <span class="in">`trt`</span> variable using the code shown below.</span>
<span id="cb13-156"><a href="#cb13-156"></a></span>
<span id="cb13-159"><a href="#cb13-159"></a><span class="in">```{r}</span></span>
<span id="cb13-160"><a href="#cb13-160"></a><span class="fu">plot</span>(<span class="fu">survfit</span>(<span class="fu">Surv</span>(vdata1<span class="sc">$</span>time, vdata1<span class="sc">$</span>status) <span class="sc">~</span> vdata1<span class="sc">$</span>trt), </span>
<span id="cb13-161"><a href="#cb13-161"></a>     <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"red"</span>), <span class="at">fun =</span> <span class="st">"cloglog"</span>, <span class="at">xlab =</span> <span class="st">"log time"</span>, <span class="at">ylab =</span> <span class="st">"log-log survival"</span>)</span>
<span id="cb13-162"><a href="#cb13-162"></a><span class="in">```</span></span>
<span id="cb13-163"><a href="#cb13-163"></a></span>
<span id="cb13-164"><a href="#cb13-164"></a>An issue with graphical assessment of proportional hazards is that it is somewhat subjective and we don't have a clear way to determine a significant violation. In this plot, however, I think the result is quite clear and we can assert with reasonable confidence that the HR for <span class="in">`trt`</span> may not in fact be constant in time.</span>
<span id="cb13-165"><a href="#cb13-165"></a></span>
<span id="cb13-166"><a href="#cb13-166"></a><span class="fu">## Time-dependent variables.</span></span>
<span id="cb13-167"><a href="#cb13-167"></a></span>
<span id="cb13-168"><a href="#cb13-168"></a>The last approach to testing for proportional hazards on a covariate is to create an interaction between the covariate and time (or some function of it). This allows the 'effect' of the covariate to vary at different times and we can assess the proportional hazards assumption by testing for the significance of this interaction term. If the p value is statistically significant this provides some evidence for a time-varying 'effect' of the covariate on survival times (i.e. the HR is NOT constant over time).</span>
<span id="cb13-169"><a href="#cb13-169"></a></span>
<span id="cb13-170"><a href="#cb13-170"></a>::: callout-note</span>
<span id="cb13-171"><a href="#cb13-171"></a>The use and interpretation of such an interaction in a Cox model is really no different to that in any model - the main difference is that in this context we are interacting a covariate with time instead of another covariate. Keep in mind of course, that it is possible to include standard covariate-covariate interactions in the Cox model as well.</span>
<span id="cb13-172"><a href="#cb13-172"></a>:::</span>
<span id="cb13-173"><a href="#cb13-173"></a></span>
<span id="cb13-174"><a href="#cb13-174"></a>So, how do we specify this time-covariate interaction term in our Cox model?</span>
<span id="cb13-175"><a href="#cb13-175"></a></span>
<span id="cb13-176"><a href="#cb13-176"></a>Well there is a trick to this that relies on first knowing two small pieces of very important information, without which you will fall victim to the same naive error that has plagued countless analysts before you.</span>
<span id="cb13-177"><a href="#cb13-177"></a></span>
<span id="cb13-178"><a href="#cb13-178"></a><span class="fu">### One simple rule about covariate values in the Cox model</span></span>
<span id="cb13-179"><a href="#cb13-179"></a></span>
<span id="cb13-180"><a href="#cb13-180"></a>**"You cannot look into the future"**</span>
<span id="cb13-181"><a href="#cb13-181"></a></span>
<span id="cb13-182"><a href="#cb13-182"></a>Terry Therneau - one of the main authors of the <span class="in">`survival`</span> package, writes on page 2 of the package's <span class="co">[</span><span class="ot">time-dependent vignette</span><span class="co">](https://cran.r-project.org/web/packages/survival/vignettes/timedep.pdf)</span>:</span>
<span id="cb13-183"><a href="#cb13-183"></a></span>
<span id="cb13-184"><a href="#cb13-184"></a>"**The key rule for time dependent covariates in a Cox model is simple and essentially the same as that for gambling: you cannot look into the future. A covariate may change in any way based on past data or outcomes, but it may not reach forward in time.**"</span>
<span id="cb13-185"><a href="#cb13-185"></a></span>
<span id="cb13-186"><a href="#cb13-186"></a>And on page 101 of <span class="co">[</span><span class="ot">Applied Survival Analysis Using R</span><span class="co">](https://xsliulab.github.io/Workshop/2021/week3/survival-analysis-book.pdf)</span>:</span>
<span id="cb13-187"><a href="#cb13-187"></a></span>
<span id="cb13-188"><a href="#cb13-188"></a>"The partial likelihood theory for survival data, introduced in Chap. 5, allows one to model survival times while accommodating covariate information. An important caveat to this theory is that the values of the covariates must be determined at time t = 0, when the patient enters the study, and remain constant thereafter. **This issue arises with survival data because such data evolve over time, and it would be improper to use the value a covariate to model survival information that is observed before the covariate’s value is known.** To accommodate covariates that may change their value over time (“time dependent covariates”), special measures are necessary to obtain valid parameter estimates. An intervention that occurs after the start of the trial, or a covariate (such as air pollution exposure) that changes values over the course of the study are two examples of time dependent variables.</span>
<span id="cb13-189"><a href="#cb13-189"></a></span>
<span id="cb13-190"><a href="#cb13-190"></a>The rule is clear: we cannot predict survival using covariate values from the future."</span>
<span id="cb13-191"><a href="#cb13-191"></a></span>
<span id="cb13-192"><a href="#cb13-192"></a>And from <span class="co">[</span><span class="ot">Logical and statistical fallacies in the use of Cox regression models</span><span class="co">](https://pubmed.ncbi.nlm.nih.gov/8546126/)</span>:</span>
<span id="cb13-193"><a href="#cb13-193"></a></span>
<span id="cb13-194"><a href="#cb13-194"></a>"A potential source of error involving the use of future information arises from the improper use of covariates in the Cox model...</span>
<span id="cb13-195"><a href="#cb13-195"></a></span>
<span id="cb13-196"><a href="#cb13-196"></a>...For example, we discuss why one should almost never use a covariate that has been averaged over a patient’s entire follow-up time as a baseline covariate. Instead, the baseline value should be used as a covariate, or the cumulative average up to each point in time should be used as a time-dependent covariate."</span>
<span id="cb13-197"><a href="#cb13-197"></a></span>
<span id="cb13-198"><a href="#cb13-198"></a>You may wonder why I am telling you this? The reason is that I think it's a common error for the naive analyst to use future covariate information in survival models. It is particularly salient to be aware of this when we are now talking about constructing a covariate-time interaction term. Because if I asked you how you would do this, I bet you a million dollars you would tell me something like "Well, I'll just interact each persons event/censoring time with the covariate we want to test". In formula terms:</span>
<span id="cb13-199"><a href="#cb13-199"></a></span>
<span id="cb13-200"><a href="#cb13-200"></a><span class="in">`vfit1 &lt;- coxph(Surv(time, status) ~ trt + age + trt:time, vdata1)`</span></span>
<span id="cb13-201"><a href="#cb13-201"></a></span>
<span id="cb13-202"><a href="#cb13-202"></a>Well you would be wrong, because in doing this, you are breaking that cardinal rule of not looking into the future (I'll show you why shortly).</span>
<span id="cb13-203"><a href="#cb13-203"></a></span>
<span id="cb13-204"><a href="#cb13-204"></a>With regards to this erroneous model specification, Terry Therneau writes on page 21 of the <span class="co">[</span><span class="ot">time-dependent vignette</span><span class="co">](https://cran.r-project.org/web/packages/survival/vignettes/timedep.pdf)</span>:</span>
<span id="cb13-205"><a href="#cb13-205"></a></span>
<span id="cb13-206"><a href="#cb13-206"></a>"This mistake has been made often enough the the coxph routine has been updated to print an error message for such attempts. The issue is that the above code does not actually create a time dependent covariate, rather it creates a time-static value for each subject based on their value for the covariate time; no differently than if we had constructed the variable outside of a coxph call. **This variable most definitely breaks the rule about not looking into the future, and one would quickly find the circularity: large values of time appear to predict long survival because long survival leads to large values for time.**"</span>
<span id="cb13-207"><a href="#cb13-207"></a></span>
<span id="cb13-208"><a href="#cb13-208"></a><span class="fu">### Event times are all-important in the Cox model</span></span>
<span id="cb13-209"><a href="#cb13-209"></a></span>
<span id="cb13-210"><a href="#cb13-210"></a>The second concept that you may have come across in your readings on survival analysis (but I would bet you probably don't remember) is that event times are where the action is at in estimating the Cox model. **At each event time the covariate values for the individual experiencing the event are compared against the values in place for all the individuals at risk at that time (i.e. in the "risk set").** Not in the past, and certainly not in the future, **but at that time**. Regression coefficients (i.e. log HRs) are then estimated as a function of these covariate values.</span>
<span id="cb13-211"><a href="#cb13-211"></a></span>
<span id="cb13-212"><a href="#cb13-212"></a><span class="fu">### Putting it all together</span></span>
<span id="cb13-213"><a href="#cb13-213"></a></span>
<span id="cb13-214"><a href="#cb13-214"></a>So, now that we know the rule about not using future covariate information and also the importance of event times in Cox model estimation, how do we use this information to construct the *correct* time-covariate interaction we alluded to above in assessing the validity of proportional hazards?</span>
<span id="cb13-215"><a href="#cb13-215"></a></span>
<span id="cb13-216"><a href="#cb13-216"></a>The "trick" is to split our data at every event time. In doing this we create a new dataset where we essentially have multi-row (counting process) data for each person. Each person's observation time is split into periods defined by **all** event times, for whatever time that person remains under observation. As an example, let's look at just the first <span class="in">`3`</span> patients in the <span class="in">`veteran`</span> dataset:</span>
<span id="cb13-217"><a href="#cb13-217"></a></span>
<span id="cb13-220"><a href="#cb13-220"></a><span class="in">```{r}</span></span>
<span id="cb13-221"><a href="#cb13-221"></a><span class="co"># Create new df with just the first 3 subjects</span></span>
<span id="cb13-222"><a href="#cb13-222"></a>vdata1_first3 <span class="ot">&lt;-</span>  vdata1 <span class="sc">|&gt;</span> </span>
<span id="cb13-223"><a href="#cb13-223"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) </span>
<span id="cb13-224"><a href="#cb13-224"></a>vdata1_first3 <span class="sc">|&gt;</span> </span>
<span id="cb13-225"><a href="#cb13-225"></a>  <span class="fu">kable</span>(<span class="at">align =</span> <span class="st">"c"</span>, <span class="at">digits =</span> <span class="dv">2</span>)</span>
<span id="cb13-226"><a href="#cb13-226"></a><span class="in">```</span></span>
<span id="cb13-227"><a href="#cb13-227"></a></span>
<span id="cb13-228"><a href="#cb13-228"></a>Each of these patients experiences the event. We can use the <span class="in">`survSplit()`</span> function to split each persons observation time by all events. When we do this we get:</span>
<span id="cb13-229"><a href="#cb13-229"></a></span>
<span id="cb13-232"><a href="#cb13-232"></a><span class="in">```{r}</span></span>
<span id="cb13-233"><a href="#cb13-233"></a><span class="co"># Split time at every event and create vector of unique event times</span></span>
<span id="cb13-234"><a href="#cb13-234"></a>event_times <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">unique</span>(<span class="fu">with</span>(vdata1_first3, time[status <span class="sc">==</span> <span class="dv">1</span>])))</span>
<span id="cb13-235"><a href="#cb13-235"></a><span class="co"># Create new df in CP form with splits at every event time</span></span>
<span id="cb13-236"><a href="#cb13-236"></a>vdata2_first3 <span class="ot">&lt;-</span> <span class="fu">survSplit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span>., vdata1_first3, <span class="at">cut =</span> event_times)</span>
<span id="cb13-237"><a href="#cb13-237"></a>vdata2_first3 <span class="sc">|&gt;</span> </span>
<span id="cb13-238"><a href="#cb13-238"></a>  <span class="fu">kable</span>(<span class="at">align =</span> <span class="st">"c"</span>, <span class="at">digits =</span> <span class="dv">2</span>)</span>
<span id="cb13-239"><a href="#cb13-239"></a><span class="in">```</span></span>
<span id="cb13-240"><a href="#cb13-240"></a></span>
<span id="cb13-241"><a href="#cb13-241"></a>You can see that Subject <span class="in">`1`</span> has the shortest observation time (<span class="in">`72`</span> days) and given there were no other event times in that period, their data remains the same. Subject <span class="in">`2`</span>, however, has the longest observation time (<span class="in">`411`</span> days) and given there are <span class="in">`3`</span> events and they are at in the *risk set* for all of those, their observation time is split into <span class="in">`3`</span> periods defined by those event timings. Subject <span class="in">`3`</span> has an observation time of <span class="in">`228`</span> days and as they are only at risk therefore for two of the three events, their observation time is split into <span class="in">`2`</span> periods. And so on - hopefully you are starting to get the picture.</span>
<span id="cb13-242"><a href="#cb13-242"></a></span>
<span id="cb13-243"><a href="#cb13-243"></a>::: callout-note</span>
<span id="cb13-244"><a href="#cb13-244"></a>One issue to be aware of with splitting time at every event is that it can lead to some very large datasets!</span>
<span id="cb13-245"><a href="#cb13-245"></a>:::</span>
<span id="cb13-246"><a href="#cb13-246"></a></span>
<span id="cb13-247"><a href="#cb13-247"></a>In this data manipulation trick we are emulating single-row/person data with multi-row/person data, but the specifications are equivalent as the covariate values remain the same for each individual. The point is that we now have a data set where the risk sets used to calculate the covariate-time interaction respect the *current* time, not a potentially future time defined by the end of observation (i.e. event/censoring) as we would have used in the naive analysis.</span>
<span id="cb13-248"><a href="#cb13-248"></a></span>
<span id="cb13-249"><a href="#cb13-249"></a>After all of that, let's finally run this model. We take our <span class="in">`137`</span> patients and use <span class="in">`survSplit`</span> to create an expanded dataset whereby observation time for each patient is split at all death times. We then use a <span class="in">`trt:time`</span> interaction to assess whether proportional hazards may hold over the duration of observation.</span>
<span id="cb13-250"><a href="#cb13-250"></a></span>
<span id="cb13-253"><a href="#cb13-253"></a><span class="in">```{r}</span></span>
<span id="cb13-254"><a href="#cb13-254"></a><span class="co">#| message: false</span></span>
<span id="cb13-255"><a href="#cb13-255"></a><span class="co">#| warning: false</span></span>
<span id="cb13-256"><a href="#cb13-256"></a><span class="co"># Split time at every event and create vector of unique event times</span></span>
<span id="cb13-257"><a href="#cb13-257"></a>event_times <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">unique</span>(<span class="fu">with</span>(vdata1, time[status <span class="sc">==</span> <span class="dv">1</span>])))</span>
<span id="cb13-258"><a href="#cb13-258"></a><span class="co"># Create new df in CP form with splits at every event time</span></span>
<span id="cb13-259"><a href="#cb13-259"></a>vdata2 <span class="ot">&lt;-</span> <span class="fu">survSplit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span>., vdata1, <span class="at">cut =</span> event_times)</span>
<span id="cb13-260"><a href="#cb13-260"></a>vfit2 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(tstart, time, status) <span class="sc">~</span> trt <span class="sc">+</span> age <span class="sc">+</span> trt<span class="sc">:</span>time, vdata2)</span>
<span id="cb13-261"><a href="#cb13-261"></a><span class="fu">tbl_regression</span>(vfit2, <span class="at">exp =</span> T)</span>
<span id="cb13-262"><a href="#cb13-262"></a><span class="in">```</span></span>
<span id="cb13-263"><a href="#cb13-263"></a></span>
<span id="cb13-264"><a href="#cb13-264"></a>The p value for the interaction term is <span class="in">`0.03`</span> and so by this third method we may also surmise that the hazards for <span class="in">`trt`</span> may not be proportional over time.</span>
<span id="cb13-265"><a href="#cb13-265"></a></span>
<span id="cb13-266"><a href="#cb13-266"></a>Out of interest - what would we have gotten in the naive analysis - i.e. where we create the interaction term using the event/censoring time?</span>
<span id="cb13-267"><a href="#cb13-267"></a></span>
<span id="cb13-270"><a href="#cb13-270"></a><span class="in">```{r}</span></span>
<span id="cb13-271"><a href="#cb13-271"></a><span class="co">#| message: false</span></span>
<span id="cb13-272"><a href="#cb13-272"></a><span class="co">#| warning: false</span></span>
<span id="cb13-273"><a href="#cb13-273"></a><span class="co"># Naive model using final observation time</span></span>
<span id="cb13-274"><a href="#cb13-274"></a>vfit3 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> trt <span class="sc">+</span> age <span class="sc">+</span> trt<span class="sc">:</span>time, vdata1)</span>
<span id="cb13-275"><a href="#cb13-275"></a><span class="fu">tbl_regression</span>(vfit3, <span class="at">exp =</span> T)</span>
<span id="cb13-276"><a href="#cb13-276"></a><span class="in">```</span></span>
<span id="cb13-277"><a href="#cb13-277"></a></span>
<span id="cb13-278"><a href="#cb13-278"></a>Hmmm - quite different... and quite wrong!</span>
<span id="cb13-279"><a href="#cb13-279"></a></span>
<span id="cb13-280"><a href="#cb13-280"></a>There is actually a quicker way to run this equivalent model without needing to first split the data, but I wanted to show you the "first-principles" approach, first. Again, on page 21 of the <span class="co">[</span><span class="ot">time-dependent vignette</span><span class="co">](https://cran.r-project.org/web/packages/survival/vignettes/timedep.pdf)</span>, a general method is outlined which relies on the *time-transform* functionality of <span class="in">`coxph()`</span>. Using this model specification, you will see that we end up with the same result.</span>
<span id="cb13-281"><a href="#cb13-281"></a></span>
<span id="cb13-284"><a href="#cb13-284"></a><span class="in">```{r}</span></span>
<span id="cb13-285"><a href="#cb13-285"></a>vfit3 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> trt <span class="sc">+</span> age <span class="sc">+</span> <span class="fu">tt</span>(trt), <span class="at">tt =</span> <span class="cf">function</span>(x,t,...) x<span class="sc">*</span>t, vdata1)</span>
<span id="cb13-286"><a href="#cb13-286"></a><span class="fu">tbl_regression</span>(vfit3, <span class="at">exp =</span> T)</span>
<span id="cb13-287"><a href="#cb13-287"></a><span class="in">```</span></span>
<span id="cb13-288"><a href="#cb13-288"></a></span>
<span id="cb13-289"><a href="#cb13-289"></a><span class="fu"># Wrap-Up</span></span>
<span id="cb13-290"><a href="#cb13-290"></a></span>
<span id="cb13-291"><a href="#cb13-291"></a>I had originally intended to make this all one post, but clearly I have gone on for too long as usual. Today we have discussed how to diagnose non-proportional hazards, but of course you are wondering about the equally important question of "what do we actually do about non-proportional hazards?"</span>
<span id="cb13-292"><a href="#cb13-292"></a></span>
<span id="cb13-293"><a href="#cb13-293"></a>I will tackle that in the Part 2 post in a few weeks, so I hope to see you then.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>